### ISSUE TITLE
PINNs solver applied to existing problem tests

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#112]
@KirillZubov and @ashutosh-b-b  The PINN solver is a major step forward in terms of readability of the PDE problem investigated. It would be extremely useful to apply/merge it to the existing test problems in NeuralNetDiffEq. Also in the test problems, now that the backward Kolmogorov equation is up and running, the Fokker-Planck (FP) equation is an obvious addition and then Mean Field Game which is a system of HJB and FP equations.

**Comment by ChrisRackauckas** [comment]
Where did the mean field game issue go?

**Comment by ChrisRackauckas** [comment]
Indeed, now that it's starting to get documented, feel free to just post some test problems and see if it's working on them. We need to keep pushing the strategies in different ways. https://github.com/SciML/NeuralNetDiffEq.jl/issues/46 is still the most puzzling thing!

**Comment by finmod** [comment]
The https://github.com/EmoryMLIP/MFGnet.jl/issues/2 has been idle since March 2 but NeuralNetDiffEq is close to solving this one without looking over their shoulders.

I suggest addressing all the test models from here: https://arxiv.org/pdf/1811.08782.pdf. You have already dealt with the DGM method very efficiently in the PNAS paper. Nevertheless, the set of test problems is good. NeuralNetDiffEq would need to add: Fokker-Planck (Kolmogorov forward), Systemic risk and Mean Field Games (FBSDE system of HJB+FP).

Still linking all these test problem is https://github.com/SciML/NeuralNetDiffEq.jl/issues/52 which should be music to @KirillZubov in terms of similar steps to PINNs. You can save time by eliminating inefficient steps in their work like local solvers and expectation/weak solution. This stuff is already up and running on github/Python and can be a good benchmark for Julia/NeuralNetDiffEq (they are using massive GPU power though).

**Comment by ChrisRackauckas** [comment]
I'm not sure what's actionable here.
