### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralPDE.jl#117]
I am wondering if this package should get a snappier name. NeuralPDE.jl? PhysicsInformedML.jl?

**Comment by ashutosh-b-b** [comment]
the former looks nice

**Comment by ChrisRackauckas** [comment]
PhysicsInformedNN.jl, PINN.jl

**Comment by freemin7** [comment]
I would also be for NeuralPDE.jl

**Comment by jonniedie** [comment]
NeuralPDE for me

**Comment by ChrisRackauckas** [comment]
Setting it up: https://github.com/SciML/NeuralNetDiffEq.jl/pull/121 . Waiting for some more comments before pulling the trigger

**Comment by ChrisRackauckas** [comment]
Done, that seemed pretty unanimous.
