### ISSUE TITLE
Slight refactoring of PINNs

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralPDE.jl#118]
It differs slightly from the intended interface. It would be good to get this corrected before doing more development. The `discretize` function is intended to produce a common numerical problem so that alternative numerical tools can be used. Here, the separation of concerns is broken because there is only one solver available because it creates an uncommon `NNPDEProblem`. What this should instead be doing is building the loss function in the discretization and then that should be used to build an `OptimizationProblem`. That optimization problem can then be accessed used and solved by users of GalacticOptim.jl or any other package since it would just have `prob.f` and `prob.u0` for the optimization. 

@KirillZubov

**Comment by KirillZubov** [comment]
ok
