### ISSUE TITLE
third derivative

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [SciML/NeuralPDE.jl#129]
how can we define **third derivative** (2D/3D) in NeuralPDE?

Thanks for your support in advance!

Best regards!

**Comment by KirillZubov** [comment]
@asdasdqwdqwfsdf  do you mean PINNs ?

**Comment by asdasdqwdqwfsdf** [comment]
@KirillZubov  I would like to use PINNs for solving high order problems.

**Comment by ChrisRackauckas** [comment]
@KirillZubov I think you're confused because you implemented it already. But, you forgot to add it to the docs, so this is mostly a docs issue for just creating an example with higher order derivatives. It's the same as before: `@derivative D'''~x`, but yes we should probably have an example. I'd suggest K-S.

**Comment by asdasdqwdqwfsdf** [comment]
@ChrisRackauckas  thanks!

**Comment by KirillZubov** [comment]
@ChrisRackauckas ok, it will be done. Also then it is worth adding at docs an example with systems of PDE and an example with Neumann boundary conditions

**Comment by asdasdqwdqwfsdf** [comment]
@KirillZubov  thanks for your support!

**Comment by asdasdqwdqwfsdf** [comment]
@KirillZubov  from the new example "3rd order derivative", the difference between numerical one and analytical one is large, why?

**Comment by KirillZubov** [comment]
@asdasdqwdqwfsdf  Currently, the high-order numerical derivative is poorly stable in the learning process. It should work better when we improve the learning strategy and support automatic differentiation.

**Comment by asdasdqwdqwfsdf** [comment]
@KirillZubov thanks for your reply!

what is limit for the highest order derivative, 10th order derivative, 100th order derivative or 10000th order derivative?

**Comment by KirillZubov** [comment]
@asdasdqwdqwfsdf  actually 4th already is a challenge.

**Comment by KirillZubov** [comment]
@asdasdqwdqwfsdf I guess, yes, but I haven't tested this equation.

**Comment by KirillZubov** [comment]
hi, @asdasdqwdqwfsdf probably, it will be interesting for you to look at this example with 4th order derivative. https://neuralpde.sciml.ai/dev/examples/pinns_example/#Example-7-:-Kuramoto%E2%80%93Sivashinsky-equation-1

**Comment by asdasdqwdqwfsdf** [comment]
> 
> 
> @asdasdqwdqwfsdf I guess, yes, but I haven't tested this equation.
hi, I have tested this equation (https://github.com/SciML/NeuralPDE.jl/issues/218).
