### ISSUE TITLE
Parameters identification

### ISSUE THREAD

**Issue by LucasPa** [SciML/NeuralPDE.jl#148]
Hi,

First of all congratulations for developing the NeuralPDE package!  I have been playing around the different examples and tutorials and although I am new at Julia, I have been able to solve some PDEs that interest me. 

I would like now to do parameters identifications. For instance using PINNs to identify the value of an unknown coefficient in a PDE from measured data. Is it possible to solve this kind of problem ?

Best,

Lucas

**Comment by ChrisRackauckas** [comment]
For now you'll want to use https://diffeqflux.sciml.ai/dev/ directly for that, but this will be something added to the PINNs.

**Comment by LucasPa** [comment]
Thank you Chris for your answer. Then I will have a look at DiffEqFlux and see how I can use that to perform identification as in :

> Raissi, M., P. Perdikaris, and G. E. Karniadakis. "Physics informed deep learning (Part II): Data-driven discovery of nonlinear partial differential equations. arXiv 2017." arXiv preprint arXiv:1711.10566.

**Comment by ChrisRackauckas** [comment]
It won't be the same as though, though it will be an order of magnitude more efficient: PINNs are a very slow way to calculate things. I'd recommend the tutorial https://diffeqflux.sciml.ai/dev/examples/pde_constrained/

**Comment by LucasPa** [comment]
OK I will have a look to this example and see how I can adapt this to my needs.

Thanks a lot !

**Comment by LucasPa** [comment]
Hi Chris,

Thanks for the hint. I have been trough and many other examples but I am not sure that diffeqflux can actually help me. I would like to identify to identify the coefficients of a Robin boundary condition of a two-dimensional PDE (that only involves x- and y-derivatives and t-derivative) from known data. 

Best,

Lucas

**Comment by ChrisRackauckas** [comment]
You'd just track the parameter in the boundary condition. It's no different from any other parameter.

I'm going to reopen this for tracking adding this to the PINNs though, since it's still something we'll want to do for completeness.
