### ISSUE TITLE
Fail to run the example

### ISSUE THREAD

**Issue by begoat** [SciML/NeuralPDE.jl#153]
I just followed tutorial with a fresh install of Julia 1.5.2(MAC) and added `NeuralPDE `

---

After running [example](https://github.com/SciML/NeuralPDE.jl#example-solving-2d-poisson-equation-via-physics-informed-neural-networks), I came across a error.

the error log is
```
ERROR: LoadError: UndefVarError: Flux not defined
Stacktrace:
 [1] top-level scope at xxx/example.jl:22
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] exec_options(::Base.JLOptions) at ./client.jl:296
 [5] _start() at ./client.jl:506
in expression starting at xxx/example.jl:22
```

![2631601478054_ pic_hd](https://user-images.githubusercontent.com/22862294/94702853-d03fe180-0370-11eb-8489-7814f87035ab.jpg)

**Comment by ChrisRackauckas** [comment]
Thanks. It was missing a `using Flux` in that example. Now fixed.
