### ISSUE TITLE
how to set a random initial value

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [SciML/NeuralPDE.jl#154]
how can we set a **random initial value** in "NeuralPDE.jl", e.g. Poisson's Equation in 2D?

Thanks in advance!

**Comment by ChrisRackauckas** [comment]
A random initial set of parameters for the neural network?

**Comment by asdasdqwdqwfsdf** [comment]
@ChrisRackauckas 

something looks like 
"
```
# Class representing the intial conditions
class InitialConditions(Expression):
    def __init__(self):
        random.seed(2 + MPI.rank(mpi_comm_world()))
    def eval(self, values, x):
        values[0] = 0.63 + 0.02*(0.5 - random.random())
        values[1] = 0.0
    def value_shape(self):
        return (2,)
"
```
-cite(https://fenicsproject.org/docs/dolfin/1.4.0/python/demo/documented/cahn-hilliard/python/documentation.html)

**Comment by ChrisRackauckas** [comment]
When setting the boundary condition like

```julia
# Boundary conditions
bcs = [u(0,y,θ) ~ 0.f0, u(1,y,θ) ~ -sin(pi*1)*sin(pi*y),
       u(x,0,θ) ~ 0.f0, u(x,1,θ) ~ -sin(pi*x)*sin(pi*1)]

```

just use some random numbers.

**Comment by asdasdqwdqwfsdf** [comment]
> 
> 
> When setting the boundary condition like
> 
> ```julia
> # Boundary conditions
> bcs = [u(0,y,θ) ~ 0.f0, u(1,y,θ) ~ -sin(pi*1)*sin(pi*y),
>        u(x,0,θ) ~ 0.f0, u(x,1,θ) ~ -sin(pi*x)*sin(pi*1)]
> ```
> 
> just use some random numbers.

@ChrisRackauckas .

How can we define such initial values using "NeuralPDE.jl", i.e., the initial values in the circle are 0.1, other points 2.?

![grafik](https://user-images.githubusercontent.com/58915493/102813738-a8897400-43c9-11eb-9c5a-99c07d1a865e.png)

**Comment by ChrisRackauckas** [comment]
`u(0,x,y) ~ IfElse.ifelse(x^2 + y^2 < 1,0.1,2)`

**Comment by asdasdqwdqwfsdf** [comment]
@ChrisRackauckas  

How to define the circle's positon, e.g. (x1, y1) denotes the circle's positon?

**Comment by ChrisRackauckas** [comment]
`u(0,x,y) ~ IfElse.ifelse((x-x1)^2 + (y-y1)^2 < 1,0.1,2)`
