### ISSUE TITLE
Automatic weighting between equations

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralPDE.jl#155]
@vedhus pointed me to https://arxiv.org/pdf/1705.07115.pdf which is a method for adaptive weighting. This can be used to weight between the various PDEs and help handle differences in relative sizing of the terms.

**Comment by ChrisRackauckas** [comment]
https://www.youtube.com/watch?v=U38hnksTVdE could be a useful source as well

**Comment by yewalenikhil65** [comment]
https://arxiv.org/abs/2009.04544

This is another nice read regarding "self-adaptive PINN", and is also used in TensorflowDiffEq as training strategy.. It tries to increase weights in the direction of high corresponding loss

**Comment by ChrisRackauckas** [comment]
This was handled.
