### ISSUE TITLE
GridTraining not defined in PhysicsInformedNN

### ISSUE THREAD

**Issue by bhilloul** [SciML/NeuralPDE.jl#161]
Dear all,
Thank you very much for your very impressive work. 
I am a complete beginner in NeuralPDE and I was trying to test the package (version 2.4.1). When I run example 1 as defined in https://neuralpde.sciml.ai/dev/examples/pinns_example/#Example-1:-Solving-the-2-dimensional-Poisson-Equation-1 I face the error "GridTraining not defined" when I write "discretization = NeuralPDE.PhysicsInformedNN(dx,chain, strategy=NeuralPDE.GridTraining())"
Could you eventually tell me what is going on?
Than you very much

**Comment by bhilloul** [comment]
Sorry, it was an Atom problem... Thank you very much again for your work!

**Comment by ChrisRackauckas** [comment]
No problem!
