### ISSUE TITLE
NeuralPDE.NNODE  non existing while used in the documentation

### ISSUE THREAD

**Issue by FredericN** [SciML/NeuralPDE.jl#168]
The first example of NeuralPDE fails. It is easy to correct:
Add : "using DifferentialEquations"
Change "NeuralPDE.NNODE(chain, opt)" to "NeuralPDE.NNRODE(chain, opt)"
The following line 
@time sol = solve(prob, NeuralPDE.NNODE(chain, opt), dt=1 / 20f0, verbose=true,
                   abstol=1e-10, maxiters=200)
in the documentation fails due to 
ERROR: UndefVarError: NNODE not defined

**Comment by KirillZubov** [comment]
I checked. This example works ok without error.

**Comment by ChrisRackauckas** [comment]
Yeah I missed this email, but it seems fine. Did you use Julia v1.5?

**Comment by FredericN** [comment]
"This is quite strange. Here is the error I get on my laptop running Julia 1.4.3:

 @time sol = solve(prob, NeuralPDE.NNODE(chain, opt), dt=1 / 20f0, verbose=true,
                   abstol=1e-10, maxiters=200)
ERROR: UndefVarError: NNODE not defined
Stacktrace:
 [1] top-level scope at ./util.jl:175

More over, when I look for the functions of NeuralPDE starting with NN I get this
> NeuralPDE.NN
NNDE         NNKolmogorov  NNPDEHan      NNPDENS       NNPDEProblem  NNRODE        NNStopping

As you can see, there is NNRODE  but not NNODE

**Comment by ChrisRackauckas** [comment]
Did you do `using NeuralPDE`?

**Comment by ChrisRackauckas** [comment]
Wait, are you on the most recent version?

**Comment by FredericN** [comment]
I have just updated Julia to version 1.5. and everything works smoothly. May be you could add a warning works only with Julia version >= 1.5?

**Comment by ChrisRackauckas** [comment]
I just upped the lower bound in Project.toml.

**Comment by FredericN** [comment]
Just done it with Julia v1.5 and it works fine. 
Thanks,
Frédéric

> Le 16 nov. 2020 à 14:19, Christopher Rackauckas <notifications@github.com> a écrit :
> 
> 
> Yeah I missed this email, but it seems fine. Did you use Julia v1.5?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

—————————————————————————————————————
Frederic Nataf
Senior Scientist CNRS
Laboratoire Jacques Louis Lions, CNRS UMR 7598, Sorbonne Université, Campus Pierre et Marie Curie
Equipe Alpines à INRIA
HPDDM Open source project: https://github.com/hpddm
An Introduction to Domain Decomposition Methods: Algorithms, Theory and Parallel Implementation: http://bookstore.siam.org/ot144/
Coordonnées: 4 place Jussieu
75252 Paris Cedex 05, France
http://www.upmc.fr/fr/universite/campus_et_sites/a_paris_et_en_idf/jussieu.html , bureau 319 Tour 15/25
mel: frederic.nataf@sorbonne-universite.fr  http://www.ann.jussieu.fr/~nataf/
Tel: 33 (0)1 44 27 93 03     PORTABLE:    07 60 01 07 96
Fax:33 (0)1 44 27 72 00
---------------------------------------------------------------------------
