### ISSUE TITLE
[IDEA] Please add an installation instruction

### ISSUE THREAD

**Issue by kookma** [SciML/NeuralPDE.jl#170]
Not in readme.md nor in documentation page https://neuralpde.sciml.ai/dev/
there is no instruction for installing NeuralPDE.jl

Side note: Link to stable documentation https://neuralpde.sciml.ai/stable/ in readme.me is broken.

**Comment by ChrisRackauckas** [comment]
You just do the standard Julia package installation: `]add NeuralPDE`. There's nothing special to it.

**Comment by ChrisRackauckas** [comment]
I guess maybe if this is someone's first Julia package it might be useful, but it seems pretty niche for that? I'd assume most people would've used DifferentialEquations.jl before and want something pretty specific if they are going to neural PDE solvers. But we can add installation instructions anyways: it would essentially be a copy paste of any other description of how to add a package.

**Comment by kookma** [comment]
@ChrisRackauckas Thank you for your reply! While it is clear for experienced user, I think newbies need to this small one line instruction! I appreciate to add this line in readme and/or Documentation.

**Comment by ChrisRackauckas** [comment]
Let's keep it open until we do it. @mkg33 it might be good to pepper it around anyways.

**Comment by mkg33** [comment]
@ChrisRackauckas I checked the broken link to the stable documentation. Indeed, it appears that the stable version doesn't exist yet. Is that so? If yes, shall we create it or leave out this link for now?
