### ISSUE TITLE
Document / cleanup special theta (θ) parameter. 

### ISSUE THREAD

**Issue by dangirsh** [SciML/NeuralPDE.jl#172]
I was surprised to find that the θ parameter from the examples was a required symbol in the arguments to dependent variables. The existence of this symbol seems to be a [hard-coded assumption in _transform_derivative](https://github.com/SciML/NeuralPDE.jl/blob/f20b0b1089ffb77e80463bec5348e5d142e82a82/src/pinns_pde_solve.jl#L119). 

If I renames or omit this symbol, I get the same error message as  #171, which is misleading / confusing.

Is θ documented in some other package / paper that I'm not aware of?

If there's a straight-forward way to remove this magic symbol, it seems worth doing. Otherwise, a big warning in the docs seems warranted.

**Comment by KirillZubov** [comment]
yeah, θ is reserved for use. it needs to fix this bug. I'll do it tomorrow.

**Comment by ChrisRackauckas** [comment]
So from the call it was cleared up that this theta is the neural network parameters and shouldn't be in the high level PDE description. It is not necessarily in the description in order for the NN method to generate the calls and it omits portability with the other PDE methods. So it can just be dropped from the description with the backend code being the same.
