### ISSUE TITLE
support ConstrainedEquation for PINNs

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#176]
Some examples of how this can be: 
```julia
using ModelingToolkit

@parameters x y
@variables u(..)
@derivatives Dy'~y
@derivatives Dxx''~x

some_f(x,y) = x^2+y^2
eq = Dy(u(x,y)) - Dxx(u(x,y)) ~ some_f(x,y)

x_domain = IntervalDomain(0.0,3.0)
left_x_domain = IntervalDomain(0.0,1.0)
right_x_domain = IntervalDomain(2.0,3.0)
y_domain = IntervalDomain(0.0,1.0)

con_eq = ConstrainedEquation([x ∈ left_x_domain ⊗ right_x_domain, y ∈ y_domain],eq) #separate domain
con2_eq = ConstrainedEquation([x ~ 0,y < 1/2], u(x,y) ~ x + y^2)
con3_eq = ConstrainedEquation(x^2+y^2<0,  eq)
```

**Comment by dangirsh** [comment]
I understood the `ProductDomain` (`⊗`) to be intended for multidimensional variables - see the comment [here](https://github.com/SciML/DifferentialEquations.jl/issues/469#issue-456786103). A new abstraction is probably needed for non-contiguous domains as like in this example.

Note that for the P2D model, I've worked-around this issue by using a symbolic IfElse (see [here](https://github.com/SciML/ModelingToolkit.jl/pull/568)) to branch the equations for each battery domain. That's implemented [here](https://github.com/aced-differentiate/DFN.jl/blob/c2575b266491c271ea58eec7945183a769cf2717/scripts/symbolic.jl#L50).

I think explicitly specifying the non-contiguous domain would be cleaner than the symbolic branch, so this should probably be left open.

**Comment by Mrzhang-hub** [comment]
> I understood the `ProductDomain` (`⊗`) to be intended for multidimensional variables - see the comment [here](https://github.com/SciML/DifferentialEquations.jl/issues/469#issue-456786103). A new abstraction is probably needed for non-contiguous domains as like in this example.
> 
> Note that for the P2D model, I've worked-around this issue by using a symbolic IfElse (see [here](https://github.com/SciML/ModelingToolkit.jl/pull/568)) to branch the equations for each battery domain. That's implemented [here](https://github.com/aced-differentiate/DFN.jl/blob/c2575b266491c271ea58eec7945183a769cf2717/scripts/symbolic.jl#L50).
> 
> I think explicitly specifying the non-contiguous domain would be cleaner than the symbolic branch, so this should probably be left open.

The implementation of P2D model using neuralPDE seems missing. Could you please share it again?
