### ISSUE TITLE
Function to pass training parameters to the next solver

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#192]
It would be more convenient for debugging and building a more flexible learning strategy to have a function that transfers the learning parameters, first of all, the trained neural network weights to the next solver. Also, it's also an opportunity to look at the intermediate result.

```julia
res1 = GalacticOptim.solve(prob,ADAM(0.1); cb = cb, maxiters=20)
prob = pass_training_parameters(res, stratagy, ...)
res2 = GalacticOptim.solve(prob,ADAM(0.001); cb = cb, maxiters=5000)
```

**Comment by ChrisRackauckas** [comment]
I think this would almost fall under the `remake` idea, but it just barely doesn't. But yes, a helper function here could be useful.
