### ISSUE TITLE
Using a loop algorithm instead of recursive for calculating the derivative 

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#193]
The loop algorithm is always better. At worst, the time complexity is the same and, at best a couple of times faster and also not required creating scope every recursively calling function.

On pseudocode, it will look something like this:
```julia
function get_numeric_loop_derivative()
    epsilon_mask = get_epsilon_mask()
    dxs = get_dxs(epsilon_mask)
    Cs =  get_finite_difference_coefficient(order_derivative)
    epsilon = 2*cbrt(eps(Float32))

    derivative = (phi,u,x,εs,order,θ) ->
        return sum([C*u(x+dx,θ,phi) for (dx,C) in zip(dxs,Cs)])/epsilon
    end
    derivative
end

```

**Comment by ChrisRackauckas** [comment]
Instead of summing an array, sum the generator expression `sum(C*u(x+dx,θ,phi) for (dx,C) in zip(dxs,Cs))` and it'll be a bit better.

**Comment by ChrisRackauckas** [comment]
No, it shouldn't be a loop. It should specialize to higher order directly.
