### ISSUE TITLE
Support TensorBoardLogger.jl or something like this.

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#194]
As @dangirsh noted, it would be very convenient to use for interpreting the results TensorBoardLogger.jl or something similar.
https://github.com/PhilipVinc/TensorBoardLogger.jl

**Comment by ChrisRackauckas** [comment]
This should be considered an upstream issue in https://github.com/SciML/GalacticOptim.jl/issues/80

**Comment by ChrisRackauckas** [comment]
This is done.
