### ISSUE TITLE
no method matching GridTraining(; dx=0.1) && MethodError: no method matching StochasticTraining(; number_of_points=20)

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [SciML/NeuralPDE.jl#195]
MethodError: no method matching GridTraining(; dx=0.1)
Closest candidates are:
  GridTraining() at /root/.julia/packages/NeuralPDE/7SDF6/src/pinns_pde_solve.jl:56 got unsupported keyword argument "dx"

Stacktrace:
 [1] top-level scope at In[6]:21

MethodError: no method matching StochasticTraining(; number_of_points=20)
Closest candidates are:
  StochasticTraining(; include_frac) at /root/.julia/packages/NeuralPDE/7SDF6/src/pinns_pde_solve.jl:62 got unsupported keyword argument "number_of_points"
  StochasticTraining(!Matched::Float64) at /root/.julia/packages/NeuralPDE/7SDF6/src/pinns_pde_solve.jl:59 got unsupported keyword argument "number_of_points"
  StochasticTraining(!Matched::Any) at /root/.julia/packages/NeuralPDE/7SDF6/src/pinns_pde_solve.jl:59 got unsupported keyword argument "number_of_points"

**Comment by ChrisRackauckas** [comment]
are you on the latest version?

**Comment by asdasdqwdqwfsdf** [comment]
Pkg.add("NeuralPDE");
Julia 1.4.2
