### ISSUE TITLE
Plot Error:

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [SciML/NeuralPDE.jl#198]
In the Example 2 : Solving the 2-dimensional ...

if we change the domain area (size/shape) from 1 to 4:
 
`domains = [x ∈ IntervalDomain(0.0,1.0) -> domains = [x ∈ IntervalDomain(-1.0,1.0),`

we will find the plot error:  Arrays have incorrect length or dimension.

So the correct plot command is `plot( ts, xs, ...)`, not plot( xs, ts, ...).

**Comment by ChrisRackauckas** [comment]
It depends on what you want to plot. If you want to plot all of the spatial domains, do that. I would agree doing (ts,xs) is likely more common than (xs,ts), so that would be worth a PR.
