### ISSUE TITLE
Why is phi([x,y],res.minimizer) an array?

### ISSUE THREAD

**Issue by drozzy** [SciML/NeuralPDE.jl#232]
Forgive the silly question...

It seems like in all examples I've encountered so far everytime after accessing the phi we always get the first element: `phi([x,y],res.minimizer)[1]`

Is there a reason it comes out as an array of size 1?

**Comment by KirillZubov** [comment]
Thanks for noticing, actually yes now `phi` always returns one value, before it was not so. Now, as I understand it, this is no longer needed. It will need to be fixed.

**Comment by KirillZubov** [comment]
@ChrisRackauckas  I think this issue is outdated and can be closed since we are returning an array now:
```julia
julia> phi(rand(1,10),res.minimizer)
1×10 Matrix{Float64}:
 0.890359  0.865627  0.791329  0.82943  0.970596  0.794722  0.807961  1.16547  1.10584  0.863407
```
or if one value then just use `first`
`first(phi([0.1],res.minimizer))`
