### ISSUE TITLE
Error in latest update_doc examples

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#235]
In Example1 2D Poisson and many other examples, there is a bug in the syntax for Discretization:

dx = 0.05
discretization = PhysicsInformedNN(chain, GridTraining(dx))

Returns:

MethodError: no method matching GridTraining()
Closest candidates are:
  GridTraining(!Matched::Any) at C:\Users\Denis\.julia\dev\NeuralPDE.jl-master\src\pinns_pde_solve.jl:64

Stacktrace:
 [1] PhysicsInformedNN(::Function, ::GridTraining) at C:\Users\Denis\.julia\dev\NeuralPDE.jl-master\src\pinns_pde_solve.jl:28
 [2] top-level scope at In[13]:3
 [3] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

**Comment by ChrisRackauckas** [comment]
`MethodError: no method matching GridTraining()` that's not the function you called?

**Comment by KirillZubov** [comment]
I think the problem is that we haven't updated the new release and it's needed to use the "master" for the current documentation

**Comment by ChrisRackauckas** [comment]
I'll take a look at the most recent doc PR and play with it before merging. I didn't quite like it, but I realized I had some detailed change in mind that is easier to do than describe so I might as well just do it instead of giving you 30 reviews 🤣 . I'll tag right after that.

**Comment by finmod** [comment]
My diagnostic is that the function selecting the 'strategy' is missing in the eight individual PINNs examples. This used to work in the large PINNs_examples.md file.

**Comment by KirillZubov** [comment]
@finmod you can update the version from "master" for now until all changes are added to the new release.
```julia
] rm NerealPDE
add NeuralPDE
```

**Comment by finmod** [comment]
Thanks. Working with the latest commit, in wave.md the callback function is missing. It should read

opt = Optim.BFGS()

cb = function (p,l)
    println("Current loss is: $l")
    return false
end
  
res = GalacticOptim.solve(prob,opt; cb = cb, maxiters=1200)
phi = discretization.phi

**Comment by ChrisRackauckas** [comment]
could you PR that?

**Comment by alokwarey** [comment]
I am getting the same error when running the 2D Poisson example. How do I resolve it?

**Comment by ChrisRackauckas** [comment]
Can you upgrade to the latest version and start a new session?

**Comment by alokwarey** [comment]
I updated NeuralPDE and tried again. Still get the same error.

**Comment by ChrisRackauckas** [comment]
Which versions?

**Comment by KirillZubov** [comment]
> Thanks. Working with the latest commit, in wave.md the callback function is missing. It should read
> 
> opt = Optim.BFGS()
> 
> cb = function (p,l)
> println("Current loss is: $l")
> return false
> end
> 
> res = GalacticOptim.solve(prob,opt; cb = cb, maxiters=1200)
> phi = discretization.phi

yeah, it's needed to either duplicate the callback function in each example or write that it is used for all examples somewhere on top.

**Comment by KirillZubov** [comment]
@ChrisRackauckas could you please add the new release so that all updates coincide with what is in the documentation.

**Comment by finmod** [comment]
Now that the pinns folder is stand alone, it is correct that the callback function should be inserted in each example separately. At present it is in poisson.md and nowhere else. The same applies to the `using.......` statement which is missing in all except poisson.md and debugging.md.

In pinns fp.md, I find that the predicted curve is much lower in the graph that the exact solution. This is unexpected and it is probaby a typo linked to the migration from the old version to this one. Also in this Fokker-Planck, it would be good to include the Duffing or Van der Pol example from the same source to show that FP systems can be handled elegantly.

As for PR request, I work on a local version of NeuralPDE and I am not quite fluent in all these PR maneuver. I am willing to learn and have read the help file but could not make sense of it since I do not work on Github.

**Comment by ChrisRackauckas** [comment]
>Now that the pinns folder is stand alone, it is correct that the callback function should be inserted in each example separately. At present it is in poisson.md and nowhere else. The same applies to the using....... statement which is missing in all except poisson.md and debugging.md.

Yes, each tutorial should be standalone and not require code from another.

**Comment by ChrisRackauckas** [comment]
>but in the latest release : GridTraining(dx=dx)

wait, why? What's the default value?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/NeuralPDE.jl/blob/master/src/pinns_pde_solve.jl#L61-L66 on the latest it's a positional arg as expected.

**Comment by KirillZubov** [comment]
yes, in the new interface positional arg  `GridTraining(dx)` but in the old version(which is the latest release) was  keyword argument `GridTraining(dx=dx)`

**Comment by ChrisRackauckas** [comment]
oh I see what you mean.

**Comment by alokwarey** [comment]
I have version v3.4.). I tried GridTraining(dx=dx). Still get the error.

**Comment by alokwarey** [comment]
I can run the example if I don't specify the strategy i.e. remove GridTraining.

**Comment by KirillZubov** [comment]
@alokwarey, update to the latest release(v3.5.0), now it matches the documentation. `GridTraining(dx)` should work.

**Comment by alokwarey** [comment]
That worked. Thanks!

**Comment by ChrisRackauckas** [comment]
Great!
