### ISSUE TITLE
SBINNs: Systems Biology INN -- PINNs for ODEs

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#239]
This extension of PINNs to ODE systems for data driven solutions belongs here. For data driven discovery, it would belong to DataDrivenDiffEq. [https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007575](url)

**Comment by ChrisRackauckas** [comment]
Yup, PINNs on ODEs can already be done. Actually, `NNODE` could do this from 2017! But... it's super inefficient to do this. We can create a tutorial around it, but this is definitely a case where the user should be pointed to DiffEqFlux.jl instead.
