### ISSUE TITLE
Upgrade to MTK5: errors and omissions in PINN examples

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#248]
In the PINN folder of docs/src/pinn, the following errors and omissions have been found:

All the examples except poisson.md have the callback function missing.

In low_level.md, get_phi is not defined.

In fp.md, the calculated curve is below the analytical solution by a substantial amount, the BFGS is very slow and does not go below 1.0. This may be a case for alternate optimizer or a succession of optimizers. It is a case where the plot should at least reflect the solution above.

In 3rd.md, the exposition of the problem in the text does not correspond to the MTK problem. The text should read u(0) = 0.0 instead of 1.0.

In 3D.md, there is a separator comma missing in the bcs conditions. Should read:

 bcs = [u(x,y,0) ~ exp(x+y)*cos(x+y) ,
       u(0,y,t) ~ exp(y)*cos(y+4t) ,
       u(2,y,t) ~ exp(2+y)*cos(2+y+4t) ,
       u(x,0,t) ~ exp(x)*cos(x+4t),
       u(x,2,t) ~ exp(x+2)*cos(x+2+4t)]

**Comment by ChrisRackauckas** [comment]
@KirillZubov it would be good to do a pass through all of the tutorials and make sure they copy-paste work now that the main interface changes are done.

**Comment by finmod** [comment]
Nice update. The callback is still missing in fp.md.

**Comment by ChrisRackauckas** [comment]
Fixed and all docs now are doctested.
