### ISSUE TITLE
Problem with First Example

### ISSUE THREAD

**Issue by Napkin314** [SciML/NeuralPDE.jl#251]
First, I want to say this package looks awesome! I'm trying to get the first example to work but I've run into a problem with what looks like a missing definition.

ERROR: LoadError: MethodError: no method matching ^(::Differential, ::Int64)
Closest candidates are:
  ^(::Float32, ::Integer) at math.jl:907
  ^(::Float16, ::Integer) at math.jl:915
  ^(::Regex, ::Integer) at regex.jl:729
  ...
Stacktrace:
 [1] macro expansion at ./none:0 [inlined]
 [2] literal_pow(::typeof(^), ::Differential, ::Val{2}) at ./none:0
 [3] top-level scope at /Users/*****/Documents/julia/ML/SciML_demo.jl:5
 [4] include(::String) at ./client.jl:457
 [5] top-level scope at REPL[24]:1
in expression starting at /Users/***(/Documents/julia/ML/SciML_demo.jl:5

The problem is the same from Atom and from Terminal, with Julia 1.5.0 and 1.5.3. The package versions I'm using are:

(SciML) pkg> status
Project SciML v0.1.0
Status `~/Documents/julia/ML/SciML/Project.toml`
  [aae7a2af] DiffEqFlux v1.32.0
  [587475ba] Flux v0.11.6
  [a75be94c] GalacticOptim v0.4.6
  [961ee093] ModelingToolkit v4.5.0
  [315f7962] NeuralPDE v3.6.0
  [429524aa] Optim v1.2.4
  [91a5bcdd] Plots v1.10.4

Can't figure out where I've gone wrong. All suggestions are welcome!

**Comment by ChrisRackauckas** [comment]
It requires MTK 5

**Comment by Napkin314** [comment]
Thought it was something I'd overlooked. Looks like it's up and running. Thank you for taking the time to help me with a dumb question, I really appreciate it!
