### ISSUE TITLE
Docs: Tutorial misleading naming

### ISSUE THREAD

**Issue by stephans3** [SciML/NeuralPDE.jl#257]
Your tutorial "2D Wave Equation with Neumann BCs" has two mistakes:
1. You describe Dirichlet boundary conditions: u(0,t)=u(1,t)=0 and not Neumann BCs
See also:
https://en.wikipedia.org/wiki/Neumann_boundary_condition
https://en.wikipedia.org/wiki/Dirichlet_boundary_condition

If you consider the derivative with respect to time "t" as the "Neumann" term then this is misleading because it is the initial value condition like in this example:
https://en.wikipedia.org/wiki/State-space_representation#Pendulum_example

2. You describe a 1-dimensional wave equation and not a 2-dimensional because as far as I know it is common ground that the dimension refers to the spatial dimension.
The dimension in time is known by the name or type of the PDE:
Poisson PDE (elliptic): no derivative in time - no temporal dimension
Heat equation (parabolic): one first-order derivative in time
Wave equation (hyperbolic): one second-order derivative in time

See for example "Consider the one-dimensional hyperbolic PDE given by" in:
https://en.wikipedia.org/wiki/Partial_differential_equation#The_energy_method

See also:
https://j-fu.github.io/VoronoiFVM.jl/stable/examples/Example106_NonlinearDiffusion1D/

Reading some title like "3D Heat equation" I expect an equation like
du/dt = a * (d^2u/dx^2 + d^2u/dy^2 + d^2u/dz^2)
with three derivatives in space.

There might be cases in which you have various derivatives in time but I am not sure whether in these (few) cases the temporal and spatial dimensions are summed up.

**Comment by ChrisRackauckas** [comment]
All of the points made here are correct. @KirillZubov can you clean that up?
