### ISSUE TITLE
Bug in PINN param_estim.md

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#271]
This section of code:

discretization = NeuralPDE.PhysicsInformedNN([chain1 , chain2, chain3],NeuralPDE.GridTraining(dt), param_estim=true, additional_loss=additional_loss)
pde_system = PDESystem(eqs,bcs,domains,[t],[x, y, z],[σ_, ρ, β], [1.0, 1.0 ,1.0])
prob = NeuralPDE.discretize(pde_system,discretization)
cb = function (p,l)
    println("Current loss is: $l")
    return false
end
res = GalacticOptim.solve(prob, BFGS(); cb = cb, maxiters=5000)
p_ = res.minimizer[end-2:end] # p_ = [9.93, 28.002, 2.667]

produces the following error:

MethodError: no method matching PDESystem(::Array{Equation,1}, ::Array{Equation,1}, ::Array{ModelingToolkit.VarDomainPairing,1}, ::Array{Num,1}, ::Array{Num,1}, ::Array{Num,1}, ::Array{Float64,1})
Closest candidates are:
  PDESystem(::Any, ::Any, ::Any, ::Any, ::Any) at C:\Users\Denis\.julia\packages\ModelingToolkit\JtDFb\src\systems\pde\pdesystem.jl:8

Stacktrace:
 [1] top-level scope at In[8]:2
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

**Comment by ashutosh-b-b** [comment]
Yes I guess this was changed to pass parameters as a dictionary,
like [here](https://github.com/SciML/NeuralPDE.jl/blob/517018c3899805e751fa0a57d37cf5070ab8b1e7/test/NNPDE_tests.jl#L533)
I ll change the documentation

**Comment by KirillZubov** [comment]
@ChrisRackauckas the issue can be closed, it is fixed
