### ISSUE TITLE
question about pinn solver

### ISSUE THREAD

**Issue by songjhaha** [SciML/NeuralPDE.jl#283]
Is the pinns solver for pde using Zygote or Flux (with autoDiff) to get the high order derivative of u to x?
I am trying to using Flux to get some second order derivative, but i found it a bit difficult in Flux because Zygote cant easily get the derivative of array to array. I am reading the source code here but still cant figure it out.

**Comment by ChrisRackauckas** [comment]
It's not.

**Comment by songjhaha** [comment]
Thank you for your reply.
