### ISSUE TITLE
How to specify parameters that depend on geometry in the PDE?

### ISSUE THREAD

**Issue by troyrock** [SciML/NeuralPDE.jl#301]
I would like to modify the Poisson example on the front page to include a term that depends on the value of y:
```
function epsilon(y)
    if y > 0.5
        return 0.1
    else
        return 0.2
    end
end

# 2D PDE
eq  = epsilon(y) * (Dxx(u(x,y)) + Dyy(u(x,y))) ~ -sin(pi*x)*sin(pi*y)
```

This gives me an error **TypeError: non-boolean (Num) used in boolean context**.  What is the correct way to do this?

**Comment by ChrisRackauckas** [comment]
Using IfElse.jl is the right way to do it until SymbolicTracing.jl is complete.
