### ISSUE TITLE
Error when trying to solve Poisson's equation with custom boundary conditions and layered dielectrics.

### ISSUE THREAD

**Issue by troyrock** [SciML/NeuralPDE.jl#303]
I'm trying to modify the Poisson example on the front page to have different boundary conditions and different material layers at different y layers.  Here is the error that I am getting followed by the code that I'm using.

**TypeError: non-boolean (Matrix{Bool}) used in boolean context
in eval at base/boot.jl:360
in top-level scope at poisson_for_layered_media.jl:87
in at SciMLBase/9EjAY/src/solve.jl:3
in #solve#468 at SciMLBase/9EjAY/src/solve.jl:3
in __solve##kw at GalacticOptim/JnLwV/src/solve.jl:137
in __solve##kw at GalacticOptim/JnLwV/src/solve.jl:137
in var"#__solve#16" at GalacticOptim/JnLwV/src/solve.jl:182
in optimize at Optim/uwNqi/src/multivariate/optimize/optimize.jl:35
in initial_state at Optim/uwNqi/src/multivariate/solvers/first_order/bfgs.jl:85
in value_gradient!! at NLSolversBase/geyh3/src/interface.jl:82
in at GalacticOptim/JnLwV/src/solve.jl:171
in at GalacticOptim/JnLwV/src/function.jl:106
in gradient at Zygote/6HN9x/src/compiler/interface.jl:58
in pullback at Zygote/6HN9x/src/compiler/interface.jl:40
in _pullback at Zygote/6HN9x/src/compiler/interface.jl:34
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at GalacticOptim/JnLwV/src/function.jl:106
in _pullback at ZygoteRules/OjfTt/src/adjoint.jl:57
in adjoint at Zygote/6HN9x/src/lib/lib.jl:191
in _apply at base/boot.jl:804
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at GalacticOptim/JnLwV/src/function.jl:104
in _pullback at ZygoteRules/OjfTt/src/adjoint.jl:57
in adjoint at base/none
in adjoint at Zygote/6HN9x/src/lib/lib.jl:191
in _apply at base/boot.jl:804
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at SciMLBase/9EjAY/src/problems/basic_problems.jl:107
in _pullback at ZygoteRules/OjfTt/src/adjoint.jl:57
in adjoint at Zygote/6HN9x/src/lib/lib.jl:191
in _apply at base/boot.jl:804
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at NeuralPDE/3vhJJ/src/pinns_pde_solve.jl:906
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at NeuralPDE/3vhJJ/src/pinns_pde_solve.jl:613
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:528
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:528
in _pullback at base/reduce.jl:501
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:501
in _pullback at base/reduce.jl:287
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:287
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:160
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:160
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:44
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:48
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:58
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/reduce.jl:93
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/none
in _pullback at NeuralPDE/3vhJJ/src/pinns_pde_solve.jl:413
in _pullback at RuntimeGeneratedFunctions/3SZ1T/src/RuntimeGeneratedFunctions.jl:112
in _pullback at ZygoteRules/OjfTt/src/adjoint.jl:57
in adjoint at Zygote/6HN9x/src/lib/lib.jl:191
in _apply at base/boot.jl:804
in _pullback at Zygote/6HN9x/src/compiler/interface2.jl
in _pullback at base/none
in macro expansion at base/none
in macro expansion at RuntimeGeneratedFunctions/3SZ1T/src/RuntimeGeneratedFunctions.jl:124
in macro expansion at NeuralPDE/3vhJJ/src/pinns_pde_solve.jl:389**

Here is my modified code (I'm new to Julia and trying to do things right so don't hesitate to make suggestions for better ways to do things unrelated to this problem):

```
using NeuralPDE, Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux
using IfElse
@parameters x y  # Why parameters and not variables?
@variables u(..)  # Why not u(x,y)?
Dxx = Differential(x)^2
Dyy = Differential(y)^2

const ldotx = -0.45
const ldotl = 0.50
const min_vl = -0.1
const vl = -0.1
const max_vl = 0.1
  
const rectx = 0
const rectl = 0.30
const min_vm = -0.1
const vm = -0.05
const max_vm = 0.1
  
const rdotx = 0.45
const rdotl = 0.50
const min_vr = -0.1
const vr = -0.1
const max_vr = 0.1
  
const min_y = -2
const max_y = 2
const min_x = -2
const max_x = 2
const sheet_y = max_y - 0.40  # sheet of charge 40 nm from the top
const quantum_top = max_y - 1.343  # top of the quantum layer
const quantum_bottom = max_y - 1.568  # bottom of the quantum layer

const sigma0 = 0.36
const epsilon_above = 76.9
const epsilon_quantum = 69.7
const epsilon_below = 76.9

function epsilon(y)
    result = IfElse.ifelse((quantum_bottom < y) & (y < quantum_top), 
              epsilon_quantum, epsilon_above)
end

function sigma(y)
    result = IfElse.ifelse((sheet_y < y), sigma0*y, sigma0*sheet_y)
end

# 2D PDE
eq  = epsilon(y)*(Dxx(u(x,y)) + Dyy(u(x,y))) ~ sigma(y)

top_edge = function(x)
    result = IfElse.ifelse((abs(x-ldotx) < ldotl/2.0), vl,
             IfElse.ifelse((abs(x-rectx) < rectl/2.0), vm,
             IfElse.ifelse((abs(x-rdotx) < rdotl/2.0), vr, 0)))
end
        
# Boundary conditions
bcs = [u(0,y) ~ 0.f0, 
       u(1,y) ~ 0.f0,
       u(x,0) ~ top_edge(x), 
       u(x,1) ~ 0.f0]

# Space and time domains
domains = [x ∈ IntervalDomain(min_x,max_x),
           y ∈ IntervalDomain(min_y, max_y)]

# Neural network
dim = 2 # number of dimensions
chain = FastChain(FastDense(dim,16,Flux.σ),FastDense(16,16,Flux.σ),FastDense(16,1))

# Discretization
dx = 0.05
discretization = PhysicsInformedNN(chain,GridTraining(dx))

pde_system = PDESystem(eq,bcs,domains,[x,y],[u])
prob = discretize(pde_system,discretization)

#Optimizer
opt = Optim.BFGS()

#Callback function
cb = function (p,l)
    println("Current loss is: $l")
    return false
end

res = GalacticOptim.solve(prob, opt, cb = cb, maxiters=1000)

```

Thanks for your patience with me. If there is another place that I should be posting things like this, don't hesitate to let me know. I hope to be able to utilize these amazing tools and also contribute to make them better. Right now, I'm learning how to use them and more about Julia.

**Comment by KirillZubov** [comment]
IfElse.ifelse is not supported yet by the parser  https://github.com/SciML/NeuralPDE.jl/issues/299 , the workaround is to use `@register `
```julia
using NeuralPDE, Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux
using IfElse
@parameters x y  # Why parameters and not variables?
@variables u(..)  # Why not u(x,y)?
Dxx = Differential(x)^2
Dyy = Differential(y)^2

const ldotx = -0.45
const ldotl = 0.50
const min_vl = -0.1
const vl = -0.1
const max_vl = 0.1

const rectx = 0
const rectl = 0.30
const min_vm = -0.1
const vm = -0.05
const max_vm = 0.1

const rdotx = 0.45
const rdotl = 0.50
const min_vr = -0.1
const vr = -0.1
const max_vr = 0.1

const min_y = -2
const max_y = 2
const min_x = -2
const max_x = 2
const sheet_y = max_y - 0.40  # sheet of charge 40 nm from the top
const quantum_top = max_y - 1.343  # top of the quantum layer
const quantum_bottom = max_y - 1.568  # bottom of the quantum layer

const sigma0 = 0.36
const epsilon_above = 76.9
const epsilon_quantum = 69.7
const epsilon_below = 76.9

function epsilon(y)
    result = IfElse.ifelse((quantum_bottom < y) & (y < quantum_top),
              epsilon_quantum, epsilon_above)
end
@register epsilon(y)
function sigma(y)
    IfElse.ifelse((sheet_y < y), sigma0*y, sigma0*sheet_y)
end
@register sigma(y)
# 2D PDE
eq  = epsilon(y)*(Dxx(u(x,y)) + Dyy(u(x,y))) ~ sigma(y)
function top_edge_(x)
    IfElse.ifelse((abs(x-ldotx) < ldotl/2.0), vl,
             IfElse.ifelse((abs(x-rectx) < rectl/2.0), vm,
             IfElse.ifelse((abs(x-rdotx) < rdotl/2.0), vr, 0)))
end
@register top_edge_(x)

# Boundary conditions
bcs = [u(0,y) ~ 0.f0,
       u(1,y) ~ 0.f0,
       u(x,0) ~ top_edge_(x),
       u(x,1) ~ 0.f0]

# Space and time domains
domains = [x ∈ IntervalDomain(min_x,max_x),
           y ∈ IntervalDomain(min_y, max_y)]

# Neural network
dim = 2 # number of dimensions
chain = FastChain(FastDense(dim,16,Flux.σ),FastDense(16,16,Flux.σ),FastDense(16,1))

# Discretization
dx = 0.05
discretization = PhysicsInformedNN(chain,GridTraining(dx))

pde_system = PDESystem(eq,bcs,domains,[x,y],[u])
prob = discretize(pde_system,discretization)

#Optimizer
opt = Optim.BFGS()

#Callback function
cb = function (p,l)
    println("Current loss is: $l")
    return false
end

res = GalacticOptim.solve(prob, opt, cb = cb, maxiters=1000)

```

**Comment by troyrock** [comment]
Thank you!  That got rid of the error.  I'm trying to figure out how to visualize the result to see if it is solving correctly.
