### ISSUE TITLE
Fourier neural operators

### ISSUE THREAD

**Issue by lamorton** [SciML/NeuralPDE.jl#309]
Nice to have: [ Fourier Neural Operators](https://github.com/zongyi-li/fourier_neural_operator).  Related to #268.

**Comment by yewalenikhil65** [comment]
@lamorton @ChrisRackauckas 

From a new package NeuralOperators.jl

https://github.com/foldfelis/NeuralOperators.jl/blob/04f2643cb2c2671de88b298ed44440bd71b6bff0/src/fourier.jl#L139

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/NeuralOperators.jl
