### ISSUE TITLE
Possibility to define vector parameters with @parameters 

### ISSUE THREAD

**Issue by killah-t-cell** [SciML/NeuralPDE.jl#311]
I want to define a parameter r that is defined as a vector in 3d space [x, y, z]. Right now I need to define x, y, z individually even if I only want to use these parameters together. Would be great to be able to `@parameters r::Vector{3, Float64}` or similar.

I am new to Julia and am honoured to start participating in this community. Thanks Chris and everyone.

**Comment by KirillZubov** [comment]
@killah-t-cell 
```julia
julia> @variables x[1:3]
1-element Vector{Vector{Num}}:
 [x₁, x₂, x₃]
julia> @variables x[1:2,1:3]
1-element Vector{Matrix{Num}}:
 [x₁ˏ₁ x₁ˏ₂ x₁ˏ₃; x₂ˏ₁ x₂ˏ₂ x₂ˏ₃]
```

**Comment by killah-t-cell** [comment]
Thanks! saved me from doing the slightly hacky `Dr(x) = [Dx(x), Dy(x), Dz(x)]`
