### ISSUE TITLE
Issue with 1D wave equation example

### ISSUE THREAD

**Issue by alexpattyn** [SciML/NeuralPDE.jl#327]
# Issue

Looking at the [1D wave equation example](https://neuralpde.sciml.ai/stable/pinn/wave/), I am not sure if the presented solution is correct. I discussed this on a [julia discourse thread](https://discourse.julialang.org/t/issue-solving-2d-wave-equation-with-modelingtoolkit-jl/62963). To briefly summarize the solution in that NeuralPDE.jl example isn't what I would expect to see, and it doesn't match the results from a [matlab wave-solver](http://www.k-wave.org/) when I try to replicate the results. 

Then when I went to convert the NeuralPDE example to a "purely" ModelingToolkit version I got a solution that looked like it was from a diffusion problem. I did have a similar problem when I wrote a custom wave-solver using a spectral method, which ended up being due to improperly defined initial conditions (i.e. du(0,x)/dx = 0 instead of the derivative of the u(0,x)). So I exchanged `Dt(u(0,x)) ~ 0.` for `Dx(u(0,x)) ~ 1-2x` in the `bcs` without it having any effect.

## Matlab Code
```
clearvars;

% =========================================================================
% SIMULATION
% =========================================================================

% create the computational grid
Lx =1;           
dx = 0.1;                 % grid point spacing in the x direction [m]    
Nx = round(Lx/dx); % number of grid points in the x (row) direction

kgrid = kWaveGrid(Nx, dx);

% define the properties of the propagation medium
medium.sound_speed = 1;  % [m/s] 

kgrid.makeTime(medium.sound_speed, [], 5);

% create initial pressure distribution
x = 0:dx:Lx-dx;
p0 = x.*(1-x);
source.p0=p0';

% define a sensor
sensor.mask = zeros(1,Nx);

% run the simulation
args = {'PMLInside', false, 'RecordMovie', true};
sensor_data = kspaceFirstOrder1D(kgrid, medium, source, sensor,args{:});
```

## Matlab Results

Keep in mind the solution below has a larger spatial dim than the NeuralPDE example, due to the fact that this wave solver is using a spectral method and has to have a perfectly-matched-layer to avoid "wrap around" effects. 

![025e99b32f49b0d76aa910db4dbb826eb8170c0f](https://user-images.githubusercontent.com/28536677/122265557-e2ce5c80-cea6-11eb-805a-3c8a2cdf268c.gif)

## Converted NeuralPDE Example

```
using Plots, DifferentialEquations, ModelingToolkit, DiffEqOperators

@parameters t, x
@variables u(..)
Dxx = Differential(x)^2
Dtt = Differential(t)^2
Dt = Differential(t)
Dx = Differential(x)

#2D PDE
C=1
eq  = Dtt(u(t,x)) ~ C^2*Dxx(u(t,x))

# Initial and boundary conditions
bcs = [u(t,0) ~ 0.,# for all t > 0
       u(t,1) ~ 0.,# for all t > 0
       u(0,x) ~ x*(1. - x), #for all 0 < x < 1
       Dt(u(0,x)) ~ 0.0, #for all  0 < x < 1
]

# Space and time domains
domains = [t ∈ (0.0,1.0),
           x ∈ (0.0,1.0)]
# Method of lines discretization
dx = 0.1
order = 2
discretization = MOLFiniteDifference([x=>dx],t)

# PDE system
pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x)])


# Convert the PDE problem into an ODE problem
prob = discretize(pdesys,discretization)

# Solve ODE problem
sol = solve(prob)

# Plot results
anim = @animate for i ∈ 1:length(sol.t)
plot(sol.u[i], label = "wave", ylims =[-0.25, 0.25])
end every 5

gif(anim, "1Dwave.gif", fps = 10)
```
## Converted NeuralPDE Results

![2f4d411c9871ba53bb63ce4b3ceb5c7d9499cb27](https://user-images.githubusercontent.com/28536677/122266669-080f9a80-cea8-11eb-8ce7-ff52b74a9afb.gif)

**Comment by ChrisRackauckas** [comment]
@KirillZubov could you look into this?

**Comment by KirillZubov** [comment]
@alexpattyn it is not NeuralPDE `discretization = MOLFiniteDifference([x=>dx],t) ` it is DiffEqOperators

**Comment by ChrisRackauckas** [comment]
Oh @alexpattyn did you have a NeuralPDE example?

**Comment by alexpattyn** [comment]
@ChrisRackauckas @KirillZubov Originally I was referring to https://neuralpde.sciml.ai/stable/pinn/wave/, but I also provided an Matlab example and another when I converted the NeuralPDE to a ModelingToolkit example.

**Comment by ChrisRackauckas** [comment]
ModelingToolkit isn't a solver, so I don't know what that last statement means. And we know that DiffEqOperators isn't generally ready to use, that's a separate issue. But this I thought was just NeuralPDE? Can someone just generate the animation from the slices of the neural network and double check?

**Comment by alexpattyn** [comment]
Running the example from the docs I referenced earilier.

![slice2](https://user-images.githubusercontent.com/28536677/122290197-7b71d600-cec1-11eb-97fb-84d5fbde72b7.png)

![slices](https://user-images.githubusercontent.com/28536677/122290202-7dd43000-cec1-11eb-8e31-221d95cf191c.gif)

**Comment by alexpattyn** [comment]
I wouldn't even say the analytical solution is correct for a wave equation. There is no outwards propagation.

**Comment by ChrisRackauckas** [comment]
Yeah that looks wrong. Worth investigating. Thanks for noticing.

**Comment by alexpattyn** [comment]
No problem. If there are any PRs I'll be happy to test them out. Then for reference:

```
(neuralpde) pkg> status
     Project neuralpde v0.1.0
      Status `~/Projects/neuralpde/Project.toml`
  [aae7a2af] DiffEqFlux v1.38.0
  [587475ba] Flux v0.12.4
  [a75be94c] GalacticOptim v1.3.0
  [961ee093] ModelingToolkit v5.19.0
  [315f7962] NeuralPDE v3.13.0
  [429524aa] Optim v1.3.0
  [91a5bcdd] Plots v1.16.5
```

**Comment by KirillZubov** [comment]
I updated wave docs. The code was a bit outdated. Now the prediction matches the stated analytical solution.

**Comment by KirillZubov** [comment]
@alexpattyn  If I understood correctly matlab solution on the x_domain =  [-2.5, 2.5] with u(t,-2.5) ~ 0, u(t,2.5) ~ 0.
and here https://neuralpde.sciml.ai/dev/pinn/wave/ x_domain =  [0.,1.]

**Comment by ChrisRackauckas** [comment]
oh

**Comment by alexpattyn** [comment]
> @alexpattyn If I understood correctly matlab solution on the x_domain = [-2.5, 2.5] with u(t,-2.5) ~ 0, u(t,2.5) ~ 0.
> and here https://neuralpde.sciml.ai/dev/pinn/wave/ x_domain = [0.,1.]

The x domain is -2.5 to 2.5 due to the wave solver using a spectral method. It implements a perfectly-matched-layer (PML) which extends the domain (from the original -0.5 & 0.5) and attenuates the waves so they don't wrap around. So technically I wouldn't say it has any BCs at u(0,-2.5) or u(0,2.5). Its just that starting @ x = -0.5 or 0.5 the waves become highly attenuated before they reach x=-2.5 or 2.5.

**Comment by KirillZubov** [comment]
it is a different task. I opened the tutorial to k-wave and the governing equation that solved  is  
![image](https://user-images.githubusercontent.com/12683885/122314486-f28a8700-cf20-11eb-9cff-823a8bf2aa2d.png)
it is reduced to a simple wave equaеtion -  Dtt(u(t,x)) = const*Dxx(u(t,x)),  when all constants
so it is definitely not a simple wave equation becouse
there is damping in your solution and the damped wave equation looks like: Dtt(u(t,x)) + νDt(u(t,x)) =  const*Dtt(u(t,x))

**Comment by KirillZubov** [comment]
> I wouldn't even say the analytical solution is correct for a wave equation. There is no outwards propagation (see my earlier matlab example).

I'm double-checked and solved analytically(by d'Alembert's solution, using a Fourier transform ) for the considered pde - https://neuralpde.sciml.ai/dev/pinn/wave/. it all is definitely correct and prediction and analytic and the same solution for domain [-2.5,2.5]. @alexpattyn Your example doesn't refer to that task although it all calls a Wave equation. 
-as Dx(u(0,x) = 0  then it should be a "standing" wave.
-and for damping oscilation it need - Dt(u(t,x)) in equation:  Dtt(u(t,x)) + C1Dt(u(t,x)) = C2(u(t,x))

```julia
xs =-2.5:0.1:2.5
ts = 0.0:0.1:1.0
analytic_sol_func2(t,x) = sum([-2.0*(pi*m*sin(pi*m)+2.0*cos(pi*m)-2.0)/(pi^3*m^3) * sin(m*pi*x)*cos(C*m*pi*t) for m in 1:1:50000])
anim = @animate for t ∈ ts
    sol =  [analytic_sol_func2(t,x) for x in xs]
    plot(sol, label = "wave",ylims =[-0.25, 0.25])
end

gif(anim, "1Dwave2.gif", fps = 10)
```
![1Dwave2](https://user-images.githubusercontent.com/12683885/122394524-c1d93a80-cf7e-11eb-90f4-2ac6488039c3.gif)

**Comment by KirillZubov** [comment]
https://github.com/SciML/NeuralPDE.jl/commit/3576450077dc441b5878afd6fea72628449e4f74

**Comment by KirillZubov** [comment]
In general, it would be great to get the prediction and add it to the doc for damping oscillation with velocity isn't zero  (Dx(u(0,x) != 0 ) and maybe with a long-term time t_domain =[0, big_t] and compare with the analytic solution.


```julia
@parameters t, x
@variables u(..)
Dxx = Differential(x)^2
Dtt = Differential(t)^2
Dt = Differential(t)
Dx = Differential(x)

#2D PDE
C= const
v =const
eq  = Dtt(u(t,x)) + v*Dt(u(t,x))~ C^2*Dxx(u(t,x))
t_end = const
# Initial and boundary conditions
bcs = [u(t,0) ~ 0.,# for all t > 0
   u(t,t_end) ~ 0.,# for all t > 0
   u(0,x) ~ x*(1. - x), #for all 0 < x < 1
    Dt(u(0,x)) ~ const (not zero), #for all  0 < x < 1
]

# Space and time domains
domains = [t ∈ (0.0,1.0),
            x ∈ (0.0,1.0)]
```

**Comment by alexpattyn** [comment]
That is something I am interested in working on if I get some time. I did have an issue with my Matlab results matching up (in a broad sense, i.e. the wave propagating outwards) with Julia when:
```
...
u(0,x) ~ x*(1. - x), #for all 0 < x < 1
Dx(u(0,x)) ~ 1-2x, #for all  0 < x < 1
...
```
But that isn't really a neuralpde issue. That could be due to modelingtoolkit being heavily under dev.

**Comment by alexpattyn** [comment]
As a first step I could work on the simple wave equation and have an 1) analytical solution, 2) ModelingToolkit (non-ML version), and then 3) NeuralPDE prediction. Afterwards I can look at including damping oscillation.

**Comment by KirillZubov** [comment]
> ModelingToolkit isn't a solver, so I don't know what that last statement means. And we know that DiffEqOperators isn't generally ready to use, that's a separate issue. But this I thought was just NeuralPDE? Can someone just generate the animation from the slices of the neural network and double check?

 @alexpattyn  it isn't ModelingToolkit (non-ML version) it is DiffEqOperators and "DiffEqOperators isn't generally ready to use"

**Comment by alexpattyn** [comment]
Alright, so I'll hold off on DiffEqOperators, and focus on the analytical solution and NeuralPDE prediction.

**Comment by alexpattyn** [comment]
> > ModelingToolkit isn't a solver, so I don't know what that last statement means. And we know that DiffEqOperators isn't generally ready to use, that's a separate issue. But this I thought was just NeuralPDE? Can someone just generate the animation from the slices of the neural network and double check?
> 
> @alexpattyn it isn't ModelingToolkit (non-ML version) it is DiffEqOperators and "DiffEqOperators isn't generally ready to use"

Also I am assuming I shouldn't open an issue for DiffEqOperators since its still under heavy dev?

**Comment by ChrisRackauckas** [comment]
No, it's because the issue and WIP PR have already been opened.

**Comment by killah-t-cell** [comment]
Started working on this. I am only getting half-decent results for some reason.

I think my analytical solution is sound:

![1Dwave_damped](https://user-images.githubusercontent.com/26853713/126747922-4af47f80-a197-40c9-b67b-c4acc540f4ca.gif)

But the prediction is a bit... moody. For example, the prediction changes significantly (for the worse) when I increase the number of max iterations. And I get different graphs when I model

Dtt(u(t,x)) + v*Dt(u(t,x))~ C^2*Dxx(u(t,x))

![Damped_wave_sol_u](https://user-images.githubusercontent.com/26853713/126748433-7f258c55-487f-4dcd-9bfa-744dc51715f2.png)

versus Dxx(u(t, x)) ~ 1 / c^2 * Dtt(u(t, x)) + v * Dt(u(t, x)) 

![Damped_wave_sol_u](https://user-images.githubusercontent.com/26853713/126748495-9928fd5a-143a-45b8-982f-6fd3b9855f27.png)

Do you have any tips in such a case? Maybe changing the training strategy or something.

Here is my code thus far:

```
using NeuralPDE, Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux
using Plots
using Quadrature,Cubature, Cuba
import ModelingToolkit: Interval, infimum, supremum

@parameters t, x
@variables u(..)
Dxx = Differential(x)^2
Dtt = Differential(t)^2
Dt = Differential(t)

# Constants
c = 2
v = 3
L = 1
@assert c > 0 && c < 2π / (L * v)

# 1D damped wave
eq = Dxx(u(t, x)) ~ 1 / c^2 * Dtt(u(t, x)) + v * Dt(u(t, x)) 
# eq = Dtt(u(t, x)) ~ c^2 * Dxx(u(t, x)) - v * Dt(u(t, x))


# Initial and boundary conditions
bcs = [u(t, 0) ~ 0.,# for all t > 0
       u(t, L) ~ 0.,# for all t > 0
       u(0, x) ~ x * (1. - x), # for all 0 < x < 1
       Dt(u(0, x)) ~ 1 - 2x # for all  0 < x < 1 
       ]

# Space and time domains
domains = [t ∈ Interval(0.0, 1.0),
           x ∈ Interval(0.0, 1.0)]

# Neural network
chain = FastChain(FastDense(2, 16, Flux.σ), FastDense(16, 16, Flux.σ), FastDense(16, 1))
initθ = Float64.(DiffEqFlux.initial_params(chain))

dx = 0.1
strategy = GridTraining(dx)
discretization = PhysicsInformedNN(chain, strategy; init_params=initθ)

pde_system = PDESystem(eq, bcs, domains, [t, x], [u])
prob = discretize(pde_system, discretization)

pde_inner_loss_functions = prob.f.f.loss_function.pde_loss_function.pde_loss_functions.contents
inner_loss_functions = prob.f.f.loss_function.bcs_loss_function.bc_loss_functions.contents
bcs_inner_loss_functions = inner_loss_functions

cb = function (p, l)
    println("Current loss is: $l")
    println("pde_losses: ", map(l_ -> l_(p), pde_inner_loss_functions))
    println("bcs_losses: ", map(l_ -> l_(p), bcs_inner_loss_functions))
    return false
end

# Optimizer
opt = Optim.BFGS()
res = GalacticOptim.solve(prob, opt; cb=cb, maxiters=1400)
phi = discretization.phi

# Analysis
ts, xs = [infimum(d.domain):dx:supremum(d.domain) for d in domains]

μ_n(k) = (v * sqrt(4 * k^2 * π^2 - c^2 * L^2 * v^2)) / (2 * L)
b_n(k) = 2 / L * -((2 * π * L - π) * k * sin(π * L * k) + ((π^2 * L - π^2 * L^2) * k^2 + 2) * cos(π * L * k) - 2) / (π^3 * k^3) # vegas((x, ϕ) -> ϕ[1] = sin(k * π * x[1]) * f(x[1])).integral[1]
a_n(k) = 2 / (L * μ_n(k)) * -(L^2 * (((2 * π * L - π) * c * k * sin(π * k) + ((π^2 - π^2 * L) * c * k^2 + 2 * L * c) * cos(π * k) - 2 * L * c) * v^2 + (8 * π * L - 2 * π) * k * sin(π * k) + ((2 * π^2 - 4 * π^2 * L) * k^2 + 8 * L) * cos(π * k) - 8 * L)) / (2 * π^3 * k^3) # vegas((x, ϕ) -> ϕ[1] = (sin((k * π * x[1]) / L) * (g(x[1]) + (v^2 * c) / 2 * f(x[1])))).integral[1]

# Sanity check
analytic_sol_func(t,x) = sum([sin((k * π * x) / L) * exp(-v^2 * c * t / 2) * (a_n(k) * sin(μ_n(k) * t) + b_n(k) * cos(μ_n(k) * t)) for k in 1:2:100]) # TODO replace 10 with 500
anim = @animate for t ∈ ts
    sol =  [analytic_sol_func(t, x) for x in xs]
    plot(sol, label="wave", ylims=[-0.25, 0.25])
end
gif(anim, "1Dwave_damped.gif", fps=100)

# Plot
u_predict = reshape([first(phi([t,x], res.minimizer)) for t in ts for x in xs], (length(ts), length(xs)))
u_real = reshape([analytic_sol_func(t, x) for t in ts for x in xs], (length(ts), length(xs)))

diff_u = abs.(u_predict .- u_real)
p1 = plot(ts, xs, u_real, linetype=:contourf, title="analytic");
p2 = plot(ts, xs, u_predict, linetype=:contourf, title="predict");
p3 = plot(ts, xs, diff_u, linetype=:contourf, title="error");
plot(p1,p2,p3)
savefig("Damped_wave_sol_u")
```

**Comment by killah-t-cell** [comment]
Here is the analytical solution and the prediction side by side in 0:0.1:1 domain

![1Dwave_damped_predict](https://user-images.githubusercontent.com/26853713/126750073-ca7f9dbe-eaf6-4ac6-bce2-62062de162f5.gif)
![1Dwave_damped](https://user-images.githubusercontent.com/26853713/126750075-d85584e0-44f3-4403-bd26-853987fbff8f.gif)

**Comment by killah-t-cell** [comment]
https://github.com/SciML/NeuralPDE.jl/pull/347 opened a PR. Looking forward to discussing this further :)

**Comment by KirillZubov** [comment]
@killah-t-cell nice, thanks. I fixed some typos and update gif's plot.
