### ISSUE TITLE
Examples with system of PDE

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#332]
there need more results of predictions for a system of PDE and compare with reliable results.

http://eqworld.ipmnet.ru/en/solutions/syspde.htm

**Comment by killah-t-cell** [comment]
I started working on this this weekend. I want to do at least 3-5 examples, but currently have only done the 2nd order constant-coefficient linear parabolic system (http://eqworld.ipmnet.ru/en/solutions/syspde/spde0101.pdf). What is the best way to submit this PR? Should I just add the examples to the docs with images? 

<img width="839" alt="Screenshot 2021-07-12 at 10 28 28" src="https://user-images.githubusercontent.com/26853713/125255592-e74a3180-e2fb-11eb-94a1-e4ab9eb50e2c.png">

**Comment by KirillZubov** [comment]
@killah-t-cell  yeap, docs is good, I guess. Create the fork and then the PR.

@ChrisRackauckas Where do you think it is better to place examples?

**Comment by ChrisRackauckas** [comment]
We should start filling a bunch in https://github.com/SciML/SciMLTutorials.jl where the compute would automatically regenerate them.

**Comment by killah-t-cell** [comment]
https://github.com/SciML/NeuralPDE.jl/pull/341 added two analytically-benchmarked systems of PDE here. Am working on a hyperbolic system as well.

**Comment by KirillZubov** [comment]
@killah-t-cell cool, if you have some question with hyperbolic , feel free ask me somewhere.
