### ISSUE TITLE
LoadError: type GridTraining has no field points

### ISSUE THREAD

**Issue by vaishnavtv** [SciML/NeuralPDE.jl#340]
Hello, 

I'm running an example with GridTraining set with some dx, but I'm getting the following error:
```julia
LoadError: type GridTraining has no field points
Stacktrace:
 [1] getproperty(x::GridTraining, f::Symbol)
   @ Base ./Base.jl:33
 [2] get_bounds(domains::Vector{Symbolics.VarDomainPairing}, eqs::Vector{Equation}, bcs::Vector{Equation}, eltypeθ::Type, dict_indvars::Dict{Symbol, Int64}, dict_depvars::Dict{Symbol, Int64}, strategy::GridTraining)
   @ NeuralPDE /packages/NeuralPDE/RwOGF/src/pinns_pde_solve.jl:602
 [3] get_bounds(domains::Vector{Symbolics.VarDomainPairing}, eqs::Vector{Equation}, bcs::Vector{Equation}, eltypeθ::Type, _indvars::Vector{Num}, _depvars::Vector{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}}, strategy::GridTraining)
   @ NeuralPDE /packages/NeuralPDE/RwOGF/src/pinns_pde_solve.jl:564
 [4] top-level scope
```
There's no way to set this attribute anywhere. Is it a bug, or am I missing something?

It seems like there have been some major changes in the source code since I used it last about a month and a half ago. I write my code using NeuralPDE's low-level API and I noticed the introduction of:
```julia
eltypeθ = eltype(initθ)
parameterless_type_θ = DiffEqBase.parameterless_type(initθ)
```
There are a lot more changes in the arguments passed to functions in pinns_pde_solve and this has rendered my older codes written using the previous version of the low-level API non-functional. Could anyone help provide some instructions on how to use packages whose source code changes in a major way in such short periods of time?
I understand if it falls mostly on users writing their codes using the low-level API, but I'd appreciate any suggestions going forward.

**Comment by KirillZubov** [comment]
@vaishnavtv yep, Neural PDE is actively developing, and a lot of change. In the docs, it has some bunch of examples of how to work with low-level api. 
https://neuralpde.sciml.ai/dev/pinn/low_level/
https://neuralpde.sciml.ai/dev/pinn/debugging/
https://neuralpde.sciml.ai/dev/pinn/system/

**Comment by vaishnavtv** [comment]
I understand. Would it be possible for you to add documentation/example code for writing low-level API that uses GPU? 
I am not able to run my low-level code (that works perfectly fine on the CPU) with modifications for GPU usage. 
It would be truly helpful if you could update the docs with a simple example.

**Comment by vaishnavtv** [comment]
It seems as if there is some problem with the high-level examples in the docs too. 
Getting the following error when I try to run the first example in NNPDE_tests_gpu.jl:

```julia
ERROR: LoadError: UndefVarError: parameters not defined
Stacktrace:
  [1] classify_arguments(job::GPUCompiler.CompilerJob, codegen_f::LLVM.Function)
    @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/irgen.jl:312
  [2] lower_byval(job::GPUCompiler.CompilerJob, mod::LLVM.Module, entry_f::LLVM.Function)
    @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/irgen.jl:354
  [3] process_entry!(job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{typeof(GPUArrays.setindex_kernel), Tuple{CUDA.CuKernelContext, CuDeviceVector{Float32, 1}, CuDeviceVector{Float32, 1}, Tuple{Int64}, Int64, UnitRange{Int64}}}}, mod::LLVM.Module, entry::LLVM.Function)
    @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/ptx.jl:84
  [4] irgen(job::GPUCompiler.CompilerJob, method_instance::Core.MethodInstance, world::UInt64)
    @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/irgen.jl:62
  [5] macro expansion
    @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/driver.jl:130 [inlined]
  [6] macro expansion
    @ /scratch/user/vish0908/.julia/packages/TimerOutputs/ZQ0rt/src/TimerOutput.jl:236 [inlined]
  [7] macro expansion
    @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/driver.jl:129 [inlined]
  [8] emit_llvm(job::GPUCompiler.CompilerJob, method_instance::Any, world::UInt64; libraries::Bool, deferred_codegen::Bool, optimize::Bool, only_entry::Bool)
    @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/utils.jl:62
  [9] emit_llvm
    @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/utils.jl:60 [inlined]
 [10] cufunction_compile(job::GPUCompiler.CompilerJob)
    @ CUDA /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:305
 [11] check_cache
    @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/cache.jl:44 [inlined]
 [12] cached_compilation
    @ /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:174 [inlined]
 [13] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{typeof(GPUArrays.setindex_kernel), Tuple{CUDA.CuKernelContext, CuDeviceVector{Float32, 1}, CuDeviceVector{Float32, 1}, Tuple{Int64}, Int64, UnitRange{Int64}}}}, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
    @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/cache.jl:0
 [14] cufunction(f::typeof(GPUArrays.setindex_kernel), tt::Type{Tuple{CUDA.CuKernelContext, CuDeviceVector{Float32, 1}, CuDeviceVector{Float32, 1}, Tuple{Int64}, Int64, UnitRange{Int64}}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ CUDA /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:294
 [15] cufunction
    @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:288 [inlined]
 [16] macro expansion
    @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:102 [inlined]
 [17] #launch_heuristic#280
    @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/gpuarrays.jl:17 [inlined]
 [18] launch_heuristic
    @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/gpuarrays.jl:17 [inlined]
 [19] gpu_call(::typeof(GPUArrays.setindex_kernel), ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::Tuple{Int64}, ::Int64, ::UnitRange{Int64}; target::CuArray{Float32, 1}, total_threads::Int64, threads::Nothing, blocks::Nothing, name::Nothing)
    @ GPUArrays /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/device/execution.jl:61
 [20] _setindex!(dest::CuArray{Float32, 1}, src::CuArray{Float32, 1}, Is::UnitRange{Int64})
    @ GPUArrays /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:169
 [21] setindex!
    @ /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:159 [inlined]
 [22] _typed_vcat!
    @ ./abstractarray.jl:1499 [inlined]
 [23] _typed_vcat(#unused#::Type{Float32}, V::NTuple{12, CuArray{Float32, 1}})
    @ Base ./abstractarray.jl:1491
 [24] typed_vcat(::Type{Float32}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::Vararg{CuArray{Float32, 1}, N} where N)
    @ Base ./abstractarray.jl:1567
 [25] vcat(::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::Vararg{CuArray{Float32, 1}, N} where N)
    @ Base ./abstractarray.jl:1483
 [26] destructure(m::Chain{Tuple{Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(identity), CuArray{Float32, 2}, CuArray{Float32, 1}}}})
    @ Flux /scratch/user/vish0908/.julia/packages/Flux/qp1gc/src/utils.jl:652
 [27] initial_params(f::Chain{Tuple{Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(identity), CuArray{Float32, 2}, CuArray{Float32, 1}}}})
    @ DiffEqFlux /scratch/user/vish0908/.julia/packages/DiffEqFlux/MUw49/src/fast_layers.jl:5
 [28] top-level scope
    @ /scratch/user/vish0908/Documents/NeuralPDE_eta/gputest1d.jl:49
in expression starting at /scratch/user/vish0908/Documents/NeuralPDE_eta/gputest1d.jl:49

```
I am running the exact same piece of code as given in the test file. This is the same error I get when I try to run the low-level code too. Am I missing something trivial?

**Comment by KirillZubov** [comment]
> I understand. Would it be possible for you to add documentation/example code for writing low-level API that uses GPU?
> I am not able to run my low-level code (that works perfectly fine on the CPU) with modifications for GPU usage.
> It would be truly helpful if you could update the docs with a simple example.

yeap, it makes sense, I open the issue.

**Comment by KirillZubov** [comment]
> I understand. Would it be possible for you to add documentation/example code for writing low-level API that uses GPU?
> I am not able to run my low-level code (that works perfectly fine on the CPU) with modifications for GPU usage.
> It would be truly helpful if you could update the docs with a simple example.

Could you please send your GPU low-level code

**Comment by vaishnavtv** [comment]
https://gist.github.com/vaishnavtv/114fe695c44458a643da4ce6f76083a8

**Comment by KirillZubov** [comment]
> It seems as if there is some problem with the high-level examples in the docs too.
> Getting the following error when I try to run the first example in NNPDE_tests_gpu.jl:
> 
> ```julia
> ERROR: LoadError: UndefVarError: parameters not defined
> Stacktrace:
>   [1] classify_arguments(job::GPUCompiler.CompilerJob, codegen_f::LLVM.Function)
>     @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/irgen.jl:312
>   [2] lower_byval(job::GPUCompiler.CompilerJob, mod::LLVM.Module, entry_f::LLVM.Function)
>     @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/irgen.jl:354
>   [3] process_entry!(job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{typeof(GPUArrays.setindex_kernel), Tuple{CUDA.CuKernelContext, CuDeviceVector{Float32, 1}, CuDeviceVector{Float32, 1}, Tuple{Int64}, Int64, UnitRange{Int64}}}}, mod::LLVM.Module, entry::LLVM.Function)
>     @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/ptx.jl:84
>   [4] irgen(job::GPUCompiler.CompilerJob, method_instance::Core.MethodInstance, world::UInt64)
>     @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/irgen.jl:62
>   [5] macro expansion
>     @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/driver.jl:130 [inlined]
>   [6] macro expansion
>     @ /scratch/user/vish0908/.julia/packages/TimerOutputs/ZQ0rt/src/TimerOutput.jl:236 [inlined]
>   [7] macro expansion
>     @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/driver.jl:129 [inlined]
>   [8] emit_llvm(job::GPUCompiler.CompilerJob, method_instance::Any, world::UInt64; libraries::Bool, deferred_codegen::Bool, optimize::Bool, only_entry::Bool)
>     @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/utils.jl:62
>   [9] emit_llvm
>     @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/utils.jl:60 [inlined]
>  [10] cufunction_compile(job::GPUCompiler.CompilerJob)
>     @ CUDA /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:305
>  [11] check_cache
>     @ /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/cache.jl:44 [inlined]
>  [12] cached_compilation
>     @ /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:174 [inlined]
>  [13] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{typeof(GPUArrays.setindex_kernel), Tuple{CUDA.CuKernelContext, CuDeviceVector{Float32, 1}, CuDeviceVector{Float32, 1}, Tuple{Int64}, Int64, UnitRange{Int64}}}}, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
>     @ GPUCompiler /scratch/user/vish0908/.julia/packages/GPUCompiler/XwWPj/src/cache.jl:0
>  [14] cufunction(f::typeof(GPUArrays.setindex_kernel), tt::Type{Tuple{CUDA.CuKernelContext, CuDeviceVector{Float32, 1}, CuDeviceVector{Float32, 1}, Tuple{Int64}, Int64, UnitRange{Int64}}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
>     @ CUDA /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:294
>  [15] cufunction
>     @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:288 [inlined]
>  [16] macro expansion
>     @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/compiler/execution.jl:102 [inlined]
>  [17] #launch_heuristic#280
>     @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/gpuarrays.jl:17 [inlined]
>  [18] launch_heuristic
>     @ /scratch/user/vish0908/.julia/packages/CUDA/M4jkK/src/gpuarrays.jl:17 [inlined]
>  [19] gpu_call(::typeof(GPUArrays.setindex_kernel), ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::Tuple{Int64}, ::Int64, ::UnitRange{Int64}; target::CuArray{Float32, 1}, total_threads::Int64, threads::Nothing, blocks::Nothing, name::Nothing)
>     @ GPUArrays /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/device/execution.jl:61
>  [20] _setindex!(dest::CuArray{Float32, 1}, src::CuArray{Float32, 1}, Is::UnitRange{Int64})
>     @ GPUArrays /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:169
>  [21] setindex!
>     @ /scratch/user/vish0908/.julia/packages/GPUArrays/Z5nPF/src/host/indexing.jl:159 [inlined]
>  [22] _typed_vcat!
>     @ ./abstractarray.jl:1499 [inlined]
>  [23] _typed_vcat(#unused#::Type{Float32}, V::NTuple{12, CuArray{Float32, 1}})
>     @ Base ./abstractarray.jl:1491
>  [24] typed_vcat(::Type{Float32}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::Vararg{CuArray{Float32, 1}, N} where N)
>     @ Base ./abstractarray.jl:1567
>  [25] vcat(::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::CuArray{Float32, 1}, ::Vararg{CuArray{Float32, 1}, N} where N)
>     @ Base ./abstractarray.jl:1483
>  [26] destructure(m::Chain{Tuple{Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(identity), CuArray{Float32, 2}, CuArray{Float32, 1}}}})
>     @ Flux /scratch/user/vish0908/.julia/packages/Flux/qp1gc/src/utils.jl:652
>  [27] initial_params(f::Chain{Tuple{Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(σ), CuArray{Float32, 2}, CuArray{Float32, 1}}, Dense{typeof(identity), CuArray{Float32, 2}, CuArray{Float32, 1}}}})
>     @ DiffEqFlux /scratch/user/vish0908/.julia/packages/DiffEqFlux/MUw49/src/fast_layers.jl:5
>  [28] top-level scope
>     @ /scratch/user/vish0908/Documents/NeuralPDE_eta/gputest1d.jl:49
> in expression starting at /scratch/user/vish0908/Documents/NeuralPDE_eta/gputest1d.jl:49
> ```
> 
> I am running the exact same piece of code as given in the test file. This is the same error I get when I try to run the low-level code too. Am I missing something trivial?

I checked the first example in NNPDE_tests_gpu.jl, it works fine with the last release. So the problem is not with NeuralPDE.
It looks like that your problem is generally with CUDA.jl
check that CUDA.jl installed correctly https://cuda.juliagpu.org/stable/installation/overview/ 

and also could you please sent `VERSION` and `] status`

**Comment by vaishnavtv** [comment]
VERSION
```
v"1.6.1"
```

and status:
```
[6e4b80f9] BenchmarkTools v1.1.1
  [052768ef] CUDA v2.6.3
  [f65535da] Convex v0.14.11
  [8a292aeb] Cuba v2.2.0
  [667455a9] Cubature v1.5.1
  [2b5f629d] DiffEqBase v6.68.1
  [aae7a2af] DiffEqFlux v1.41.0
  [0c46a032] DifferentialEquations v6.17.2
  [26cc04aa] FiniteDifferences v0.12.14
  [587475ba] Flux v0.12.1
  [f6369f11] ForwardDiff v0.10.18
  [0c68f7d7] GPUArrays v6.4.1
  [a75be94c] GalacticOptim v2.0.3
  [14197337] GenericLinearAlgebra v0.2.5
  [b6b21f68] Ipopt v0.7.0
  [033835bb] JLD2 v0.4.11
  [98e50ef6] JuliaFormatter v0.15.1
  [5078a376] LazyArrays v0.1.0
  [961ee093] ModelingToolkit v5.23.0
  [6405355b] Mosek v1.1.3
  [1ec41992] MosekTools v0.9.4
  [76087f3c] NLopt v0.6.3
  [315f7962] NeuralPDE v3.14.0
  [429524aa] Optim v1.3.0
  [91a5bcdd] Plots v1.19.2
  [d330b81b] PyPlot v2.9.0
  [67601950] Quadrature v1.9.0
  [8a4e6c94] QuasiMonteCarlo v0.2.3
  [295af30f] Revise v3.1.17
  [90137ffa] StaticArrays v1.2.7
  [0c5d862f] Symbolics v1.3.0
  [592b5752] Trapz v2.0.2
  [0e69188a] VectorizedRoutines v0.1.0
```

**Comment by vaishnavtv** [comment]
I get this warning whenever I try to run any GPU code:
```
Warning: Your Tesla K80 GPU does not meet the minimal required compute capability (3.7.0 < 5.0).
│ Some functionality might not work. For a fully-supported set-up, please use an older version of CUDA.jl
```
Do you think this is the cause of the issue?

**Comment by KirillZubov** [comment]
I'm not sure, you use CUDA v2.6.3, try to update to CUDA v3.3.

**Comment by vaishnavtv** [comment]
You seem to be right. I'm getting the same error:
```julia
ERROR: LoadError: UndefVarError: parameters not defined
``` 
when I try to test CUDA. I appreciate the prompt assistance. 
In any case, could you still add an example in your documentation for  low-level API using GPU? It'd be immensely helpful.

**Comment by KirillZubov** [comment]
I opened the issue so that will be added soon https://github.com/SciML/NeuralPDE.jl/issues/342

**Comment by vaishnavtv** [comment]
@KirillZubov were you able to run the code I posted?

**Comment by KirillZubov** [comment]
@vaishnavtv not yet, 
I have a question. Why do you prefer low-level? What are you missing with high level? I'm trying to figure out what can be improved more

**Comment by vaishnavtv** [comment]
Our lab is investigating different training strategies to improve the stability of the PINNs solver. This involves updating the collocation points at which the loss functions are computed, and also allows us to look at the gradients of all the individual loss functions, including additional losses, if any. 
We've been getting by so far with just the CPU, but we'd like to pursue our research in higher-dimensional problems, in which case, training on GPU becomes essential. 

I don't think there are any major improvements to make on your part, we've been getting fairly consistent results with the examples we've run so far. I suppose the only major problem I've had so far is that the low-level API has changed enough in the last couple of months to render my two-month old code non-functional. But like you said, the package is constantly developing, and such behavior is to be expected. I sincerely appreciate how quickly y'all have been able to assist us though, thanks!

**Comment by KirillZubov** [comment]
Thanks for the answer. Yep, I tried to implement a low-level api that it was useful for debugging and PINNs investigators.  Cool, that is works in this way.
