### ISSUE TITLE
Reduce precompile time

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#368]
https://discourse.julialang.org/t/22-seconds-to-3-and-now-more-lets-fix-all-of-the-differentialequations-jl-universe-compile-times/66313

- [ ] first, remove all `using` that don't use

**Comment by killah-t-cell** [comment]
good first issue?

**Comment by ChrisRackauckas** [comment]
Maybe not? Really digging into compile times takes a bit of knowhow, but it doesn't require NeuralPDE-specific knoweldge.
