### ISSUE TITLE
retrieving PINN result

### ISSUE THREAD

**Issue by RainerHeintzmann** [SciML/NeuralPDE.jl#376]
In the examples, given [here](https://neuralpde.sciml.ai/stable/pinn/2D/), as opposed to reshaping, the code below may be a slightly more elegant way to retrieve the PINN information:
```julia
        u_real = collect(analytic_sol_func(t,x,y) for y in ys, x in xs);
        u_predict = collect(Array(phi([t,x,y], res.minimizer))[1] for y in ys, x in xs);
```

It would be great, if there was a simple function to retrieve the result in the form of an array. Maybe by introducing a dispatch like `phi(domains, res.minimizer)`?

**Comment by KirillZubov** [comment]
Related to the issue: https://github.com/SciML/NeuralPDE.jl/issues/357

**Comment by ChrisRackauckas** [comment]
This is addressed with the new symbolic_discretize.
