### ISSUE TITLE
Error regarding complex function in boundary condition (MethodError: no method matching decompose(::Num))

### ISSUE THREAD

**Issue by BuddhiLW** [SciML/NeuralPDE.jl#387]
When I run the following boundary conditions:

```julia
# Initial and boundary conditions
bcs = [ρ(t,0) ~ ρ(t,L),
       v(t,0) ~ v(t,L),
       Dt(v(t,0)) ~ Dt(v(t,L)),
       ρ(0,x) ~ ρₕ + real(δρ(0,x)),
       v(0,x) ~ vₕ + real(δv(0,x))]
```

with δρ and δv:
```julia
k=2π/L;
λ=k^2*c₀^2/100
ω=k*(vₕ+c₀)
γ=complex(λ,ω)


δρ(t,x)=δρ₀*exp(complex(0,k*x))*exp(-γ*t)
δv(t,x)=δv₀*exp(complex(0,k*x))*exp(-γ*t)
```

I get an error relative to the δρ, δv complex numbers' definition. If I remove these terms from the boundary conditions, the solver works.

```julia
MethodError: no method matching decompose(::Num)
Closest candidates are:
  decompose(!Matched::Integer) at float.jl:555
  decompose(!Matched::Float16) at float.jl:557
  decompose(!Matched::Float32) at float.jl:568
  ...

isfinite(x::Num) at float.jl:453
exp(z::Complex{Num}) at complex.jl:642
δρ(t::Int64, x::Num) at neuralPDE.jl:37
top-level scope at neuralPDE.jl:47
eval at boot.jl:360 [inlined]
eval_in_module(fully_qualified_module_name::Vector{Symbol}, expr::Expr) at JuliaSnail.jl:160
eval_tmpfile(tmpfile::String, modpath::Vector{Symbol}, realfile::String, linenum::Int64) at JuliaSnail.jl:190
top-level scope at none:1
eval at boot.jl:360 [inlined]
eval_in_module(fully_qualified_module_name::Vector{Symbol}, expr::Expr) at JuliaSnail.jl:160
macro expansion at JuliaSnail.jl:698 [inlined]
(::Main.JuliaSnail.var"#28#32"{Sockets.TCPSocket})() at task.jl:411
```

How could I use these boundary conditions?

Minimum Working Example source: https://github.com/BuddhiLW/wlq-carflow/blob/main/NeuralPDE/neuralPDE.jl

**Comment by KirillZubov** [comment]
@BuddhiLW complex numbers are not supported, only real numbers.

**Comment by KirillZubov** [comment]
You can calculate the norm or the real part of complex numbers,

or also  represent the problem as a system with two variables
h(t, x) = [u(t, x),  v(t, x)] where u - the real part and v  - the imaginary part 
p = u(t, x) + i*v(t, x)

2.2. Example Schrodinger Equation
https://arxiv.org/pdf/1711.10561.pdf

**Comment by BuddhiLW** [comment]
Yes, I ended up analytically calculating the norm. It worked.

But, it would be interesting if there was a wrapping around Symbolic.jl, or something of the sort, which would do it for us automatically.

Anyhow, thank you for the paper and mention of treating the problem as two variables - it's structurally similar to how complex functions are treated in mathematics.

**Comment by KirillZubov** [comment]
@BuddhiLW cool, could you please share the code?

**Comment by BuddhiLW** [comment]
Of course! It's on my first comment; last line

https://github.com/BuddhiLW/wlq-carflow/blob/main/NeuralPDE/neuralPDE.jl

In the orgmode file, in the same directory, there is some discussion and deduction
