### ISSUE TITLE
Support solving equations in a mesh

### ISSUE THREAD

**Issue by killah-t-cell** [SciML/NeuralPDE.jl#389]
It would be awesome to support the ability to use NeuralPDEs to solve equations in a mesh. 

<img width="292" alt="Screenshot 2021-09-08 at 07 26 04" src="https://user-images.githubusercontent.com/26853713/132451417-f11f0f67-6efd-43ef-b105-f2e831870ba0.png">

This is super important for fluid models. Basically a user would set up a mesh, specify initial conditions where the equation is not 0, and then use NeuralPDE to solve the time-evolution of the equations. 

I don't know if this is outside of the NeuralPDE scope or if it can be hacked together right now already (if so, do let me know).

This is somewhat related to https://github.com/SciML/ModelingToolkit.jl/issues/526. Because this would necessarily involve writing initial conditions that say: `u(0, x) ~ cos(x) if x < radius`

I spoke to Chris about this but I wanted to also open an issue here.

**Comment by KirillZubov** [comment]
this can be done with a `@register`
```julia
using IfElse
radius_ =10
function ifelsef(x)
	if (x < radius_) cos(x) else 0. end
    # IfElse.ifelse(x < radius_, cos(x), 0.)
end
@register ifelsef(x)

ifelsef_.(rand(1,10))
```

**Comment by KirillZubov** [comment]
@killah-t-cell what do you mean - use NeuralPDEs to solve equations in a mesh. Could you describe it in a little more detail?

**Comment by killah-t-cell** [comment]
I think this solves my problem exactly. I thought it wasn't possible to specify the initial values on a grid-level. But if we can, then this is great.

**Comment by killah-t-cell** [comment]
@KirillZubov when I try to solve this with a more complicated expression I get an error `LoadError: ArgumentError: Cannot convert Sym to Float64 since Sym is symbolic and Float64 is concrete. Use `substitute` to replace the symbolic unwraps.`

Am I doing something wrong here?

```julia
@parameters t x v
@variables f(..) E(..) 
Dx = Differential(x)
Dt = Differential(t)
Dv = Differential(v)

# Constants
μ_0 = 1.25663706212e-6 # N A⁻²
ε_0 = 8.8541878128e-12 # F ms⁻¹
e   = 1.602176634e-19 # Coulombs
m_e = 9.10938188e-31 # Kg
v_th = sqrt(2)

eqs = [Dt(f(t,x,v)) ~ - v * Dx(f(t,x,v)) - e/m_e * E(t,x) * Dv(f(t,x,v))
       Dx(E(t,x)) ~ e*n_0/ε_0 * (Dx(f(t,x,v)) - 1)]

# Boundaries and initial conditions
function ic_f(x)
	if (x < 0.2) 1/(v_th * sqrt(2π)) * exp(-v^2/(2*v_th^2)) else 0. end
end

@register ic_f(x)

bcs = [f(0,x,v) ~ ic_f(x),
       E(0,x) ~ e*n_0/ε_0 * (Dx(f(0,x,v)) - 1)]

domains = [t ∈ Interval(0.0, 1.0),
           x ∈ Interval(0.0, 1.0), 
           v ∈ Interval(0.0, 1.0)]

# Neural Network
chain = [FastChain(FastDense(3, 16, Flux.σ), FastDense(16,16,Flux.σ), FastDense(16, 1)),
         FastChain(FastDense(2, 16, Flux.σ), FastDense(16,16,Flux.σ), FastDense(16, 1))]
initθ = map(c -> Float64.(c), DiffEqFlux.initial_params.(chain))

discretization = NeuralPDE.PhysicsInformedNN(chain, QuadratureTraining(), init_params= initθ)
@named pde_system = PDESystem(eqs, bcs, domains, [t,x,v], [f(t,x,v), E(t,x)])
prob = SciMLBase.discretize(pde_system, discretization)

# Solve
opt = Optim.BFGS()
res = GalacticOptim.solve(prob, opt, maxiters=1000)
```
