### ISSUE TITLE
Example of integro-differential equation does not work

### ISSUE THREAD

**Issue by dapias** [SciML/NeuralPDE.jl#403]
Hello. I am testing the code [here](https://neuralpde.sciml.ai/stable/pinn/integro_diff/#Integro-Differential-Equations)  and got an error with the first couple of lines
```
using ModelingToolkit, DomainSets
@parameters t
@variables i(..)
Ii = Integral(t in DomainSets.ClosedInterval(0, t))
```
This rises: 
> TypeError: non-boolean (Num) used in boolean context

**Comment by killah-t-cell** [comment]
For what is worth I just tested this and it worked for me. Try ] up to make sure you get the latest version of the packages.

<img width="1138" alt="Screenshot 2021-09-22 at 10 07 58" src="https://user-images.githubusercontent.com/26853713/134306406-30d8c162-8830-4ba1-99c8-67fbe7226699.png">

**Comment by dapias** [comment]
Thank you. I apologise. It works with the latest version of the packages in Julia1.6.

**Comment by killah-t-cell** [comment]
No problem!

**Comment by ChrisRackauckas** [comment]
Soon v1.6 will be the new LTS for Julia which will make this simpler.

**Comment by dapias** [comment]
Could you please check the next part of the example? I have got problems with the command `pde_system`. After this:
```
using NeuralPDE, Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux, DomainSets
import ModelingToolkit: Interval, infimum, supremum

@parameters t
@variables i(..)
Di = Differential(t)
Ii = Integral(t in DomainSets.ClosedInterval(0, t))
eq = Di(i(t)) + 2*i(t) + 5*Ii(i(t)) ~ 1
bcs = [i(0.) ~ 0.0]
domains = [t ∈ Interval(0.0,2.0)]
chain = Chain(Dense(1,15,Flux.σ),Dense(15,1))
initθ = Float64.(DiffEqFlux.initial_params(chain))

strategy_ = GridTraining(0.05)
discretization = PhysicsInformedNN(chain,
                                   strategy_;
                                   init_params = nothing,
                                   phi = nothing,
                                   derivative = nothing)
pde_system = PDESystem(eq,bcs,domains,[t],[i(t)])
```julia
I got:
> ERROR: UndefKeywordError: keyword argument name not assigned
Stacktrace:
 [1] PDESystem(eqs::Equation, bcs::Vector{Equation}, domain::Vector{Symbolics.VarDomainPairing}, ivs::Vector{Num}, dvs::Vector{Num}, ps::SciMLBase.NullParameters) (repeats 2 times)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/iEq0Q/src/systems/pde/pdesystem.jl:70
 [2] top-level scope
   @ REPL[31]:1

**Comment by killah-t-cell** [comment]
That one is our bad 

Do `@named pde_system = PDESystem(eq,bcs,domains,[t],[i(t)])` and it should work

**Comment by killah-t-cell** [comment]
https://github.com/SciML/NeuralPDE.jl/pull/404

**Comment by dapias** [comment]
@killah-t-cell thank you! I was able to run the whole example :)
