### ISSUE TITLE
Test on a simple integrodifferential PDE

### ISSUE THREAD

**Issue by dapias** [SciML/NeuralPDE.jl#406]
One of the simplest integrodifferential PDEs comes from the so-called [Bouchaud trap model](https://arxiv.org/pdf/cond-mat/9601012.pdf). The equation is

![CodeCogsEqn (2)](https://user-images.githubusercontent.com/5333281/134465182-a9d7eaa6-8fbf-4daa-b12f-f5c442a7b64a.gif)

P(E,t) is the probability of finding the system at a trap with energy E and at time t, and beta is a parameter related to the inverse of temperature. The equation has a solution in the Laplace domain that can be compared with a numerical solution. 

So far, in the [documentation](https://neuralpde.sciml.ai/stable/pinn/integro_diff/#Integro-Differential-Equations), there is only one example of an ordinary integrodifferential equation (ordinary in contrast to partial) that cannot be enough to cover more complex cases. I think we can use this model as a harder validation problem.

So far, what I have tried is (also posted in [stackoverflow](https://stackoverflow.com/questions/69290327/integrodifferential-pde-with-neuralpdes-julia) ):
```julia
using NeuralPDE, Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux, DomainSets
import ModelingToolkit: Interval, infimum, supremum

@parameters t E
@variables i(..)

Dt = Differential(t)
DE = Differential(E)
IE = Integral(E in DomainSets.OpenInterval(0,Inf))

beta = 2.0;
eq = Dt(i(t, E)) + exp(-beta*E)*i(t, E) - IE(i(t,E)*exp(-beta*E))*exp(-E) ~ 0
bcs = [i(0., E) ~ exp(-E)]
domains = [t ∈ Interval(0.0,100.0), E ∈ Interval(0.0, 10.0)]

chain = Chain(Dense(1,15,Flux.σ),Dense(15,1))
initθ = Float64.(DiffEqFlux.initial_params(chain));

strategy_ = GridTraining(0.05)
discretization = PhysicsInformedNN(chain,
                                   strategy_;
                                   init_params = nothing,
                                   phi = nothing,
                                   derivative = nothing)

@named pde_system = PDESystem(eq,bcs,domains,[t, E],[i(t, E)])

prob = NeuralPDE.discretize(pde_system,discretization)

```

This piece of code leads to the error: 
> KeyError: key * not found

Ps: I am using Juliav1.6, ModelingToolkit v6.4.7 and NeuralPDE v4.0.0

**Comment by KirillZubov** [comment]
1) the problem with integrand `i(t,E)*exp(-beta*E)`. The integral doesn't handle compound expressions, only `IE(i(t,E))`.

2) Inf interval is also not supported yet
relates to https://github.com/SciML/NeuralPDE.jl/issues/386

**Comment by KirillZubov** [comment]
Support compound expressions for integrand https://github.com/SciML/NeuralPDE.jl/issues/407

**Comment by killah-t-cell** [comment]
@dapias we just implemented the ability to integrate in infinite integrals. I am also working on composite integrals here https://github.com/SciML/NeuralPDE.jl/pull/409 (your example is already supported in this PR, but I want to clean it up before we release it).

**Comment by KirillZubov** [comment]
@dapias so now it should work. Could you please check the result?
```julia
using Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux, DomainSets
import ModelingToolkit: Interval, infimum, supremum

@parameters t E
@variables i(..)

Dt = Differential(t)
DE = Differential(E)
IE = Integral(E in DomainSets.ClosedInterval(0,Inf))

beta = 2.0;
eq = Dt(i(t, E)) + exp(-beta*E)*i(t, E) - IE(i(t,E)*exp(-beta*E))*exp(-E) ~ 0
bcs = [i(0., E) ~ exp(-E)]
domains = [t ∈ Interval(0.0,100.0),
           E ∈ Interval(0.0, 10.0)]

numhid=16
chain = FastChain(FastDense(2, numhid, Flux.σ), FastDense(numhid, numhid, Flux.σ), FastDense(numhid, 1))
initθ = Float64.(DiffEqFlux.initial_params(chain))

strategy_ = NeuralPDE.GridTraining([5.0, 0.5])
discretization = NeuralPDE.PhysicsInformedNN(chain,
                                            strategy_,
                                            init_params = initθ)

@named pde_system = PDESystem(eq,bcs,domains,[t, E],[i(t, E)])

prob = NeuralPDE.discretize(pde_system,discretization)

cb = function (p,l)
    println("Current loss is: $l")
    return false
end

res = GalacticOptim.solve(prob, BFGS(); cb = cb, maxiters=100)

xs = 0.0:10.0:100.0
ys = 0.0:1.0:10.0
phi = discretization.phi
u_predict = collect(Array(phi([x,y], res.minimizer))[1] for y in ys, x in xs);
plot(xs,ys,u_predict,linetype=:contourf,label = "predict")

```
![inf_integral](https://user-images.githubusercontent.com/12683885/140992628-204d6ca8-bacb-4526-8c78-7b059b1fab35.png)

**Comment by ChrisRackauckas** [comment]
Closing at it now works.
