### ISSUE TITLE
NNPDENS tests are failing

### ISSUE THREAD

**Issue by killah-t-cell** [SciML/NeuralPDE.jl#411]
I am working on this PR https://github.com/SciML/NeuralPDE.jl/pull/409. It is small, and doesn't touch NNPDENS at all, but about 2 days ago the CI started to fail in the NNPDENS tests with an error:

```
ERROR: Not implemented: convert TrackedArray{…,Vector{Float64}} to TrackedArray{…,Vector{Float32}}
```

You can find the whole stacktrace here https://github.com/SciML/NeuralPDE.jl/pull/409/checks?check_run_id=3817269601

Running the tests locally, I also see an error `Display Error: ERROR: type TerminalPDEProblem has no field u0` coming from line 20:   

https://github.com/SciML/NeuralPDE.jl/blob/23253b90eee3aeeb029782fb12cea631b90bb769/test/NNPDENS_tests.jl#L20

I am not sure why this is happening. I doubt it has anything to do with my PR, but if it does then feel free to close this issue.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/StochasticDiffEq.jl/pull/439
