### ISSUE TITLE
Got "MethodError: no method matching PDESystem" after following copy pastable code from https://neuralpde.sciml.ai/dev/pinn/poisson/

### ISSUE THREAD

**Issue by michaeljehan** [SciML/NeuralPDE.jl#416]
<img width="1126" alt="Screen Shot 2021-10-16 at 10 50 11 PM" src="https://user-images.githubusercontent.com/68639241/137593904-bcb20402-b547-47a5-9d1f-d135c96bc6c5.png">
I tried running the Poisson Eq example, but i got this error

**Comment by ChrisRackauckas** [comment]
You're on an old version of ModelingToolkit. Do you have v6? For Julia, do you have v1.6?

**Comment by ChrisRackauckas** [comment]
This is just a versioning issue.
