### ISSUE TITLE
Issue MethodError

### ISSUE THREAD

**Issue by 2020new** [SciML/NeuralPDE.jl#417]
by applying 
eq  = Dxx(u(x,y)) + Dyy(u(x,y)) ~ -sin(pi*x)*sin(pi*y) 
I have got the following message:

MethodError: no method matching hash(::Sym{Real, Base.ImmutableDict{DataType, Any}}, ::UInt64)

Thanks for your help 
Kritiker

**Comment by ChrisRackauckas** [comment]
Fixed on newer versions.
