### ISSUE TITLE
First IDE test failed

### ISSUE THREAD

**Issue by KirillZubov** [SciML/NeuralPDE.jl#418]
https://github.com/SciML/NeuralPDE.jl/blob/23253b90eee3aeeb029782fb12cea631b90bb769/test/IDE_tests.jl#L26

![image](https://user-images.githubusercontent.com/12683885/138513576-43724aaa-48eb-41eb-be9a-d4df32176b3d.png)

**Comment by killah-t-cell** [comment]
@KirillZubov the new Zygote fixes did **_not_** fix this unfortunately. Everything else is working, but it seems like those tests are still failing. I wonder what is going on here.
