### ISSUE TITLE
How to get the mathematical expression of Neural Network.

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/NeuralPDE.jl#439]
In fact, the fully-connected neural network itself is a mathematical mapping, which can be expressed by a mathematical expression.

Not symbolic regression interpolation.

Simple multi-layer perception itself is a mathematical expression. 

just return a mathematical expression from neural network model in Julia.

**Comment by ChrisRackauckas** [comment]
Neural networks are not defined in this library. Ask this question in Flux or DiffEqFlux
