### ISSUE TITLE
Deep learning for symbolic mathematics

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralPDE.jl#44]
https://arxiv.org/pdf/1912.01412.pdf

Could make use of ModelingToolkit for the representation and build a solver!

**Comment by chinglamchoi** [comment]
The code and data generation methods for this paper have finally been released (few hours ago)! https://github.com/facebookresearch/SymbolicMathematics

**Comment by zzj0402** [comment]
Working on reading the paper and replicating their result in the codebase.

**Comment by zzj0402** [comment]
https://julialang.slack.com/archives/C6A044SQH/p1593504459281700

**Comment by zzj0402** [comment]
- [ ] understand Julia neural network training
- [ ] experiment on Julia transformer
- [ ] replicate the torch model
- [ ] replicate the torch training utilities
- [ ] replicate prediction utility

**Comment by zzj0402** [comment]
https://github.com/chengchingwen/Transformers.jl/issues/11

**Comment by ChrisRackauckas** [comment]
Moved to Symbolics.jl
