### ISSUE TITLE
Kuramoto–Sivashinsky equation

### ISSUE THREAD

**Issue by cruzchue** [SciML/NeuralPDE.jl#445]
Dear SciML/NeuralPDE;

First, many thanks for providing your code.  I hope I can fit it for our research problem.

I have a question regarding your Kuramoto–Sivashinsky example. I basically copied/pasted your [code](https://github.com/SciML/NeuralPDE.jl/blob/master/docs/src/pinn/ks.md)  (also tried the same example provided at [neuralPDE website](https://neuralpde.sciml.ai/stable/pinn/ks/#Kuramoto%E2%80%93Sivashinsky-equation) ).

However, the prediction is different than the one reported (see figure - top left).  That is, the prediction looks sigmoidal instead of gaussian.  Any hints or suggestions about why this is happening?.  As mentioned above, the code is the same as yours.

![KS](https://user-images.githubusercontent.com/20096271/143727742-b7411b5b-4559-42c3-9eb6-184d56f01abc.png)

Regards;

Eduardo

**Comment by ChrisRackauckas** [comment]
Don't use direct BFGS with GridTraining. Use QuasiRandomSample with the ADAM->BFGS mixed optimizer default of GalacticOptim and you'll generally see much better results.

**Comment by cruzchue** [comment]
I did two changes following your comment.  

1.- The [line](https://github.com/SciML/NeuralPDE.jl/blob/a19c52cbf53a5ab9cbfb1609722a3fe10b2aa4ae/docs/src/pinn/ks.md?plain=1#L64): 
> discretization = PhysicsInformedNN(chain, GridTraining([dx,dt]))

was commented out and replaced by:

> discretization = PhysicsInformedNN(chain,QuasiRandomTraining(50))

2.- also, the [lines](https://github.com/SciML/NeuralPDE.jl/blob/a19c52cbf53a5ab9cbfb1609722a3fe10b2aa4ae/docs/src/pinn/ks.md?plain=1#L73-L74): 

> opt = Optim.BFGS()
> res = GalacticOptim.solve(prob,opt; cb = cb, maxiters=2000)

were commented out and replaced by:

> res = GalacticOptim.solve(prob, ADAM(0.01); cb = cb, maxiters=2000)

I just got those replacement lines from the [first page](https://github.com/SciML/NeuralPDE.jl) and I am pretty much blind of what I have done.  Well, the predictions improved; that is, the sigmoidals are gone and the gaussian-like curves are back (see Figure below), but still far from the expected curves. Anyway, if there were any extra  recommendation, it is more than welcome.

![mod02](https://user-images.githubusercontent.com/20096271/143822189-2fbbfcd8-b4aa-4729-a53d-3d925cddfaef.png)

**Comment by ChrisRackauckas** [comment]
Well yeah, that's expected with ADAM. You'd need more iterations. I said don't use ADAM, use the default ADAM+BFGS.

```julia
res = GalacticOptim.solve(prob,ADAM(),cb = cb_,maxiters=400)
prob = remake(prob,u0=res.minimizer)
res = GalacticOptim.solve(prob,BFGS(),cb = cb_,maxiters=2000)
```

**Comment by cruzchue** [comment]
thanks for the suggestions,  I did the changes.   

In short, the outcome was not as expected.  I mean, predictions got negative values again (from -1 to -3.5, see Figure).   I will play a bit with the code; hopefully it will work.  Thanks anyway.

Regards;

Eduardo

![AdamBFGS](https://user-images.githubusercontent.com/20096271/143947103-d1e9b73b-c153-4d32-8976-2698b0574ec4.png)

**Comment by ChrisRackauckas** [comment]
Interesting. It looks like it's not optimizing well. @KirillZubov any suggestions?

**Comment by KirillZubov** [comment]
adaptive derivative nn is worked here. Interesting why [origin code](https://neuralpde.sciml.ai/stable/pinn/ks/#Kuramoto%E2%80%93Sivashinsky-equation) work before and don't work now. 

```julia
using NeuralPDE, Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux
import ModelingToolkit: Interval, infimum, supremum

using QuasiMonteCarlo
using Quadrature

@parameters x, t
@variables u(..), Dxu(..) ,Dxxu(..) ,Dxxxu(..), O1(..), O2(..), O3(..)
Dt = Differential(t)
Dx = Differential(x)

α = 1
β = 4
γ = 1
eq = Dt(u(x,t)) + u(x,t)*Dxu(x,t) + α*Dx(Dxu(x,t)) + β*Dx(Dxxu(x,t)) + γ*Dx(Dxxxu(x,t)) ~ 0

u_analytic(x,t;z = -x/2+t) = 11 + 15*tanh(z) -15*tanh(z)^2 - 15*tanh(z)^3
du(x,t;z = -x/2+t) = 15/2*(tanh(z) + 1)*(3*tanh(z) - 1)*sech(z)^2

bcs_ = [u(x,0) ~ u_analytic(x,0),
       u(-10,t) ~ u_analytic(-10,t),
       u(10,t) ~ u_analytic(10,t),
       Dxu(-10,t) ~ du(-10,t),
       Dxu(10,t) ~ du(10,t)]


ep = (cbrt(eps(eltype(Float64))))^2/6
#adaptive derivative nn
der = [Dxu(x,t) ~ Dx(u(x,t)) + ep*O1(x,t) ,
       Dxxu(x,t) ~ Dx(Dxu(x,t))+ ep*O2(x,t),
       Dxxxu(x,t) ~ Dx(Dxxu(x,t))+ ep*O3(x,t)]
bcs = [bcs_; der;]
# Space and time domains
domains = [x ∈ Interval(-10.0,10.0),
           t ∈ Interval(0.0,1.0)]

# Neural network
chains = [[FastChain(FastDense(2,12,Flux.tanh),FastDense(12,12,Flux.tanh),FastDense(12,1)) for _ in 1:4];
         [FastChain(FastDense(2,4,Flux.σ),FastDense(4,1)) for _ in 1:3];
         ]
# Discretization
dx = 0.4; dt = 0.2
grid_strategy = GridTraining([dx,dt])

# quasirandom_strategy = NeuralPDE.QuasiRandomTraining(200;sampling_alg = LatinHypercubeSample())
# quadrature_strategy = NeuralPDE.QuadratureTraining()

initθ = map(c -> Float64.(c), DiffEqFlux.initial_params.(chains))
discretization = PhysicsInformedNN(chains, grid_strategy, init_params = initθ)
dep_vars = [u(x, t),Dxu(x,t) ,Dxxu(x,t) ,Dxxxu(x,t), O1(x,t), O2(x,t), O3(x,t)]
@named pde_system = PDESystem(eq,bcs,domains,[x,t],dep_vars)
prob = discretize(pde_system,discretization)

cb = function (p,l)
    println("Current loss is: $l")
    return false
end

opt = Optim.BFGS()
res = GalacticOptim.solve(prob,opt; cb = cb, maxiters=3000)
prob = remake(prob,u0=res.minimizer)
res = GalacticOptim.solve(prob,opt; cb = cb, maxiters=1000)
phi = discretization.phi[1]


using Plots

xs,ts = [infimum(d.domain):dx:supremum(d.domain) for (d,dx) in zip(domains,[dx/10,dt])]

u_predict = [[first(phi([x,t],res.minimizer)) for x in xs] for t in ts]
u_real = [[u_analytic(x,t) for x in xs] for t in ts]
diff_u = [[abs(u_analytic(x,t) -first(phi([x,t],res.minimizer)))  for x in xs] for t in ts]

p1 =plot(xs,u_predict,title = "predict")
p2 =plot(xs,u_real,title = "analytic")
p3 =plot(xs,diff_u,title = "error")
plot(p1,p2,p3)
```
![ad_der](https://user-images.githubusercontent.com/12683885/144121419-e475239b-0f82-41d6-bd2a-6955ad61ceab.png)

**Comment by cruzchue** [comment]
Many thanks.  Indeed, the latest code runs well and I got a very similar result.    I have extra questions, but probably first try by myself, just not to clutter things here.

**Comment by ChrisRackauckas** [comment]
Awesome.
