### ISSUE TITLE
How to use GPU

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/NeuralPDE.jl#449]
[2-dimensional PDEs with GPU](https://neuralpde.sciml.ai/stable/pinn/2D/)
but i canot find where is the setting of GPU

**Comment by killah-t-cell** [comment]
it is here `initθ = CuArray(Float64.(DiffEqFlux.initial_params(chain)))`

**Comment by Runfa-Zhang** [comment]
> it is here `initθ = CuArray(Float64.(DiffEqFlux.initial_params(chain)))`

# Many thanks for your help
