### ISSUE TITLE
Should we default to domain decomposition?

### ISSUE THREAD

**Issue by killah-t-cell** [SciML/NeuralPDE.jl#451]
By now, several papers have been written about how domain decomposition may help increase PINN accuracy. We can already do that now thanks to Kirill's Neural Adapter implementation. But this is not embedded in the API at all.

My questions are: should we make the API decompose the domain reasonably by default? Are there use-cases where this is not desirable? 

As a corollary, are there other things we should do to increase PINN accuracy?

Would love to hear your thoughts!

**Comment by ChrisRackauckas** [comment]
And it also reduces generalization though, so there's a non-trivial trade-off. We should make it easy but a choice.

**Comment by Runfa-Zhang** [comment]
> By now, several papers have been written about how domain decomposition may help increase PINN accuracy. We can already do that now thanks to Kirill's Neural Adapter implementation. But this is not embedded in the API at all.
> 
> My questions are: should we make the API decompose the domain reasonably by default? Are there use-cases where this is not desirable? 
> 
> As a corollary, are there other things we should do to increase PINN accuracy?
> 
> Would love to hear your thoughts!
> 
> 

# I'm interesting with your disscuse，so could you please give a example of Adapter implementation？ I just find transfor learning in document

**Comment by ChrisRackauckas** [comment]
Closing as I think this is solved as a no due to the generalization trade-off, but we can continue discussing if the research finds an answer.
