### ISSUE TITLE
How many boundary points and internal points？

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/NeuralPDE.jl#453]
How many boundary points and internal points？when use **GridTraining(dx)**
![example plot](https://user-images.githubusercontent.com/45444680/145510718-dd131fcd-aa72-46ff-8ac5-9d3c5ae98c9c.png)
for example:
```
# Space and time domains
domains = [t ∈ Interval(0,10),
           x ∈ Interval(0,10)]

# Discretization
dx = 2

# Neural network
discretization = PhysicsInformedNN(chain = FastChain(FastDense(2,16,Flux.σ),FastDense(16,16,Flux.σ),FastDense(16,1)), 
                                   GridTraining(dx); 
                                   init_params = Float64.(DiffEqFlux.initial_params(chain)))
```
1 only select left and lower boundary points？or on the four sides？and how many？

2 internal points are 4x4=16？is this right?

**Comment by KirillZubov** [comment]
you can check with code
```julia
@parameters x, y
@variables u(..)
eq = u(x,y) ~ 0.
bcs = [u(0.,0.) ~ u(0.,0.),u(x,0.) ~ u(x,0.)]

domains = [x ∈ Interval(0.0,10.0),y ∈ Interval(0.0,10.0)]
chain = FastChain((x,p) -> x)

chain([1],Float64[])
strategy_ = NeuralPDE.GridTraining(2.0)
discretization = NeuralPDE.PhysicsInformedNN(chain,strategy_;init_params = Float64[])
@named pde_system = PDESystem(eq,bcs,domains,[x],[u(x)])
prob = NeuralPDE.discretize(pde_system,discretization)

julia> pde_train_data =prob.f.f.loss_function.pde_loss_function.pde_loss_functions.contents[1].train_set
2×25 Matrix{Float64}:
 2.0  4.0  6.0  8.0  10.0  2.0  4.0  6.0  8.0  10.0  2.0  4.0  …  10.0  2.0  4.0  6.0  8.0  10.0   2.0   4.0   6.0   8.0  10.0
 2.0  2.0  2.0  2.0   2.0  4.0  4.0  4.0  4.0   4.0  6.0  6.0      6.0  8.0  8.0  8.0  8.0   8.0  10.0  10.0  10.0  10.0  10.0

bcs_train_data =[prob.f.f.loss_function.bcs_loss_function.bc_loss_functions.contents[i].train_set for i in 1:2]


julia> bcs_train_data[1]
2×1 Matrix{Float64}:
 0.0
 0.0

julia> bcs_train_data[2]
 2×6 Matrix{Float64}:
  0.0  2.0  4.0  6.0  8.0  10.0
  0.0  0.0  0.0  0.0  0.0   0.0

julia> size(pde_train_data)
(2, 25)

julia> size(bcs_train_data[1])
(2, 1)

julia> size(bcs_train_data[2])
(2, 6)
```

**Comment by KirillZubov** [comment]
in one dimensional  `x = collect(0:2:10)`  - 6 points 
the full train set will be 6*6=36
but in the boundary condition, we have  `u(0.,0.)` one point is not counted because  5*5 =25
all points that are defined in the condition are subtracted from the complete set


for boundary conditions
the first condition is one point therefore set is `(0,0)`
the second condition `u (x, 0.) `therefore 
```
 2×6 Matrix{Float64}:
  0.0  2.0  4.0  6.0  8.0  10.0
  0.0  0.0  0.0  0.0  0.0   0.0
```

**Comment by Runfa-Zhang** [comment]
> in one dimensional  `x = collect(0:2:10)`  - 6 points 
> the full train set will be 6*6=36
> but in the boundary condition, we have  `u(0.,0.)` one point is not counted because  5*5 =25
> all points that are defined in the condition are subtracted from the complete set
> 
> 
> for boundary conditions
> the first condition is one point therefore set is `(0,0)`
> the second condition `u (x, 0.) `therefore 
> ```
>  2×6 Matrix{Float64}:
>   0.0  2.0  4.0  6.0  8.0  10.0
>   0.0  0.0  0.0  0.0  0.0   0.0
> ```

## Many thanks for your kind help, now the problem is understanded clearly-
