### ISSUE TITLE
How many network models when solve the system of eqs?

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/NeuralPDE.jl#467]
like [example](https://neuralpde.sciml.ai/dev/pinn/system/)
![](https://user-images.githubusercontent.com/45444680/147386018-3c241dcc-80de-45f5-a0f7-6bf43a747c15.png)
How many network model when solve the system of eqs?
one network model to 3 output $u1, u2$ and $u3$ as follows Fig?（please wait for loading fig）
![](https://user-images.githubusercontent.com/45444680/147386116-2ff088f1-2a23-40f9-b797-2a7298246470.png)
or 3 network models to $u1, u2$ and $u3$ respectively as follows Fig?（please wait for loading fig）
![](https://user-images.githubusercontent.com/45444680/147386118-bb73afc7-706e-42b1-8b1d-322d76b7c549.png)

**Comment by killah-t-cell** [comment]
If your chain has 3 networks then it has 3 models.

**Comment by Runfa-Zhang** [comment]
> If your chain has 3 networks then it has 3 models. 

#Thanks very much！
