### ISSUE TITLE
DistributionsAD dependency problem

### ISSUE THREAD

**Issue by develooper1994** [SciML/NeuralPDE.jl#473]
I can't install NeuralPDE
There is problemlem with "DistributionsAD" dependency. There are very restricted dependencies of "DistributionsAD"

**Comment by ChrisRackauckas** [comment]
DiffEqFlux is the only thing in the dependency chain and it allows any of the latest minor version v0.6+ of DistributionsAD. That includes every release since Jun 15, 2020. You're looking at the wrong repo. Feel free to continue the discussion but I'm closing since there's not thing to fix here.
