### ISSUE TITLE
Example on PDE System to be updated

### ISSUE THREAD

**Issue by francescocalisto** [SciML/NeuralPDE.jl#502]
The first example here (https://github.com/SciML/NeuralPDE.jl/blob/34a82a757e07a967e396dc67d99fab565aa8cb4d/docs/src/pinn/system.md) needs to be updated: `prob.f.f.loss_function.pde_loss_function.pde_loss_functions.contents` throws an error and the `build_loss_function` needs `nothing` as sixth argument.

**Comment by zoemcc** [comment]
I knew there were a few calls to that style of `inner_loss_function` contents introspections lying around in the docs but I need to go find them and remove them.  I had forgotten that the way that I split up the `discretize` into `discretize_inner_functions` would break that method of introspection completely.  I'll fix this this week.  Thanks!

**Comment by ChrisRackauckas** [comment]
I updated docs and put strict mode on them so tests now fail if any doc tutorial fails to solve.

**Comment by ChrisRackauckas** [comment]
The inner usage docs are also completely changed in v5 so it just uses `symbolic_discretize`. Much simpler 😅
