### ISSUE TITLE
Register NeuralPDELogging

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralPDE.jl#503]
Hey @vchuravy, how do you register subpackages like you do in KernelAbstractions.jl?

https://github.com/SciML/NeuralPDE.jl/tree/master/lib/NeuralPDELogging

**Comment by vchuravy** [comment]
Like so: https://github.com/JuliaGPU/KernelAbstractions.jl/commit/0b49db5cc2de89c0fb9676f6933794f9c43b5daa#commitcomment-69199056

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NeuralPDELogging

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/NeuralPDELogging
