### ISSUE TITLE
How to using additional_loss input 3D data.  

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/NeuralPDE.jl#589]
How to input 3D data using [additional_loss](https://neuralpde.sciml.ai/dev/tutorials/param_estim/)？

![image](https://user-images.githubusercontent.com/45444680/185732621-c004679e-a3bf-402e-ab34-5f2fd33be365.png)

the data of u(x,y,0) as follow:
```
t_=zeros(101) #Vector[0,0,0,..,0]
x_=[i for i in 0:1:100] #Vector[0,1,2,..,100]
y_=[i for i in 0:1:100] #Vector[0,1,2,..,100]
u_=[zeros(101) for i in 0:1:100] #Matrix[101x101]
```

and ther is just one chain (not 3), how to modify the following code：

```
init_params = [Flux.destructure(c)[1] for c in [chain1,chain2,chain3]]
acum =  [0;accumulate(+, length.(init_params))]
sep = [acum[i]+1 : acum[i+1] for i in 1:length(acum)-1]

(u_ , t_) = data
len = length(data[2])

function additional_loss(phi, θ , p)
    return sum(sum(abs2, phi[i](t_ , θ[sep[i]]) .- u_[[i], :])/len for i in 1:1:3)
end
```

**Comment by ChrisRackauckas** [comment]
You just index it as 2D in the loss. But `u_=[zeros(101) for i in 0:1:100] #Matrix[101x101]` that is incorrect, `u_` is not a matrix, it's an array of arrays, which is why matrix indexing wouldn't work on it.
