### ISSUE TITLE
How to use GPU to [chain1,chian2]?

### ISSUE THREAD

**Issue by Runfa-Zhang** [SciML/NeuralPDE.jl#594]
[Using GPUs](https://neuralpde.sciml.ai/stable/tutorials/gpu/)
```
using Lux
chain = Chain(Dense(3,inner,Lux.σ),
              Dense(inner,inner,Lux.σ),
              Dense(inner,inner,Lux.σ),
              Dense(inner,inner,Lux.σ),
              Dense(inner,1)) 
ps = Lux.setup(Random.default_rng(), chain)[1]
ps = ps |> Lux.ComponentArray |> gpu .|> Float64
```
when chain=[chain1,chain2,...], how to use GPU?

**Comment by ChrisRackauckas** [comment]
Just make `ps` be an array of `gpu`'d initialized values.

**Comment by YichengDWu** [comment]
Lux supports named Chain now. It should be just wrapping them in a `Chain(u = chain_1, v = chain_2)` and setting up the params.
