### ISSUE TITLE
Treating states properly, second encounter

### ISSUE THREAD

**Issue by YichengDWu** [SciML/NeuralPDE.jl#605]
I just realized that the recent PR #604 did not fix anything. As `Phi` is a mutable field of immutable `PhysicsInformedNN`. The related source code is a bit messy. Adapting states should be done inside `PhysicsInformedNN`. But there are too many situations to deal with and I don't want to fix it right away.  For me, I just want to assume that the input `chain` is always a `Lux.Chain`, not vectors. If there are multiple dependent variables, then wrap them with another Chain, like `Chain(u = chain_u, v = chain_v)`. We can use `keys(chain)==depvars` to check if there are multiple outputs. The advantage of doing this is that we can initialize the parameters and states at once. Then `discretization.Phi` should probably be a named tuple so we don't need to remember the order of dependent variables.

**Comment by ChrisRackauckas** [comment]
I think that's reasonable. This was special cased before Chain could do that, and now that it can, we should aggressively simplify the code and interface.

**Comment by YichengDWu** [comment]
It was a bad idea to wrap them in a new `Chain`. I was not thinking correctly. It should've been just a named tuple because `initialstates` and `initialparameters` both work on named tuples, and we can nicely call `phi.u`.

**Comment by YichengDWu** [comment]
I guess simply putting `Setsfield.@set!` can correctly mutate `Phi`.

**Comment by YichengDWu** [comment]
Moved to #687
