### ISSUE TITLE
Higher approximation order `numeric_derivative`

### ISSUE THREAD

**Issue by xtalax** [SciML/NeuralPDE.jl#641]
I noticed that you are using the second approximation order centered difference for your numeric approximations of derivatives, would you like to have an option to use higher order approximations? 

We have an implementation of the fornberg algorithm which can generate the stencil for arbitrary approximation and derivative order, would it be worthwhile for me to spin this out in to a package that can be used here?

**Comment by ChrisRackauckas** [comment]
Higher order would be numerically unstable.

**Comment by xtalax** [comment]
It does appear to be stable for even order derivs at least, or is this a NeuralPDE specific thing? First order derivs are using the 2nd order centered scheme, but I thought this was unconditionally unstable
