### ISSUE TITLE
Have a training strategy for PreDefined Points

### ISSUE THREAD

**Issue by sathvikbhagavan** [SciML/NeuralPDE.jl#644]
For training PINNs, can we have a strategy where the user can sample points themselves and feed it into training? This way, they can handle if the system requires very specific discretization

cc: @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
For NNODE, tstops is would be a way to do this. But for general training yes this could be a good idea for say precomputing shocks

**Comment by sathvikbhagavan** [comment]
>For NNODE, tstops is would be a way to do this

Can you explain how tstops would work? IIUC, those are extra timepoints the solver steps into.


I was thinking more in terms of a strategy having an array of these generated points which we use in `generate_loss` function to compute loss like: https://github.com/SciML/NeuralPDE.jl/blob/master/src/ode_solve.jl#L272

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas can I close this as https://github.com/SciML/NeuralPDE.jl/pull/723 added this feature?
