### ISSUE TITLE
Pricing options using NeuralNetDiffEq

### ISSUE THREAD

**Issue by EeeasyBreezy** [SciML/NeuralPDE.jl#68]
Hi, guys!
I'm trying to implement option pricing on some abstract underlying asset using ANN approximation for each time period using different `x0 ` intial states (price of underlying asset). I've have an option with only one underlying asset, so we could also price it with Black-Sholes method, so I can make BS-value an expected one

In terms of NeuralNetDiffEq there is the following problem TerminalPDEProblem under consideration:

```
d = 1
tspan = (0.0f0, 1.0f0)
dt = 0.1
m = 70 # number of trajectories (batch size)
r = 0.05f0
sigma = 0.04f0
strikePrice = 28
g(X) = max(sum(X .- strikePrice), 0)
f(X, u, σᵀ∇u, p, t) = r .* u
μ_f(X, p, t) = r .* X
σ_f(X, p, t) = Diagonal(0.04f0* X) #Matrix d x d
prob = TerminalPDEProblem(g, f, μ_f, σ_f, x0, tspan)
hls = 100 #hide layer size
opt = Flux.ADAM(0.0001)
```

I have a collection of prices for underlying asset as follows (a collection of initial states `x0`):
`assetCostPerDayCollection = [36.6f0, 37.2f0, 37.5f0, 39.2f0, 40.2f0, 40.0f0, 39.7f0]`

And a collection of expected option prices as follows:
`blackSholesOptionCostPerDay = [ 9.965574f0, 10.565577f0, 10.865576f0, 12.565577f0, 13.565577f0, 13.365576f0, 13.065577f0 ]`

Then I'm running a solution for each `x0`:
```
opt = Flux.ADAM(0.0001)
u0 = Flux.Chain(Dense(d, hls, relu),
        Dense(hls, hls, relu),
        Dense(hls, 1))
σᵀ∇u = Flux.Chain(
        Dense(d + 1, hls, relu),
        Dense(hls, hls, relu),
        # Dense(hls, hls, relu), # if turned on we get the same result, but with more time
        Dense(hls, d),
    )
pdealg = NNPDENS(u0, σᵀ∇u, opt = opt)
evaluationTime = @elapsed answer = solve(
        prob,
        pdealg,
        verbose = true,
        maxiters = 300,
        trajectories = m,
        alg = EM(),
        dt = dt,
        pabstol = 1f-6,
    )
```

After running `solve` for a problem for each `x0`, written above, I obtain the following results for each period of time:
`Option prices: Any[11.175135f0, 11.756061f0, 12.0082035f0, 13.761024f0, 15.023212f0,14.787739f0, 14.440373f0]`

The solution gives me the following plot:
![plot](https://user-images.githubusercontent.com/27430678/75984058-c816e500-5efa-11ea-9d73-2ae7847bf7d9.png)

Actually it looks like ANN approximation is close to expected values in terms of trend change of the price, but it has a strange bias which is approximatly 1.2846 for each time frame.
Do you have any idea of why it may be happening? Is that something I should expect or the is a problem in my code? 

What I tried to do to avoid make this situation better:

- increase iterations number (up to 1000)
- increase batch size (up to 100)
- decrease learning rate (down to 0.00001)
- change discretization step (down to 0.001)
- change ANN architecture (reducing the number of layers, changing activation function on layers)

None of these seems to be making a rapid change in how solution gonna look like at the end.
I was not able to obtain any major improvement to it.

Any help is appriciated.
Sincerely, Alex

**Comment by ChrisRackauckas** [comment]
Interesting that it does look like a straight bias. @KirillZubov do you have time to look into this?

**Comment by KirillZubov** [comment]
ok, I will look into it

**Comment by KirillZubov** [comment]
@EeeasyBreezy could you share the full code that gives the results above?

**Comment by KirillZubov** [comment]
@EeeasyBreezy could you share the full code that gives the results above?

**Comment by EeeasyBreezy** [comment]
Sure
[Cure.zip](https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl/files/4293891/Cure.zip)

**Comment by KirillZubov** [comment]
@EeeasyBreezy thanks

**Comment by EeeasyBreezy** [comment]
@KirillZubov forget that, please, take this one)
The first one has an invoke of a deleted stub function
[Cure.zip](https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl/files/4293939/Cure.zip)

**Comment by KirillZubov** [comment]
@EeeasyBreezy do you sure that you need the one-dimensional case (d = 1)?

**Comment by EeeasyBreezy** [comment]
Not quite
I took a 1-dimensional problem so I can estimate the quality of the solution easily.
To estimate quality for 2 and higher dimensions I need to search somewhere data about option prices with 2 and more underlying assets. 1-dim problem is the simplest one and moreover there is analytical solution to estimate the quality and build plots

**Comment by KirillZubov** [comment]
@EeeasyBreezy  I checked. I got the same result with NNPDEHan alg. First of all, I suspect that something is wrong with the option pricing model, but still, I cannot completely exclude that the algorithm works correctly. But if this is so, then I do not understand what is the matter. Try experimenting with the model: change the parameters, add dependence on σᵀ∇u in your model and etc.

**Comment by EeeasyBreezy** [comment]
@KirillZubov ok, I'll try to
do not close this issue, please, I'll write updates here if I'm able to gain more information

**Comment by KirillZubov** [comment]
@EeeasyBreezy  ok

**Comment by ChrisRackauckas** [comment]
Moving to HighDimPDE.jl
