### ISSUE TITLE
Issue with NNStopping Example code

### ISSUE THREAD

**Issue by fswalden** [SciML/NeuralPDE.jl#680]
I can't get the optimal stopping algorithm to work with NNStopping. I receive a UndefVarError referring to the NeuralPDE.NNStopping object instantiated on the call to "solve" at the end of the example code. Does anyone have any advice? Has anyone made this code work?

(Julia v. 1.8.2)

**Comment by alecloudenback** [comment]
It seems like the [example this is referring to ](https://docs.sciml.ai/NeuralPDE/v4.5/examples/optimal_stopping_american/) is not part of the current documentation. Further, it seems like `NNStopping` was removed from NeuralPDE, even though [it's still an exported variable](https://github.com/SciML/NeuralPDE.jl/blob/e45047de217655e298e3061c09225444e8249610/src/NeuralPDE.jl#L57). Unfortunately, I haven't been able to find the right components to update this for the current SciML codebase but am also interested in this example.

**Comment by sathvikbhagavan** [comment]
`NNStopping` has been moved to HighDimPDE.jl - https://github.com/SciML/HighDimPDE.jl/pull/81

**Comment by alecloudenback** [comment]
Cool! Technically looks like it *will be moved* but hasn't been merged yet? I'll try to come back to this once it's merged into HighDimPDE

**Comment by ChrisRackauckas** [comment]
It has merged. Closing
