### ISSUE TITLE
Multithreaded test suite

### ISSUE THREAD

**Issue by staticfloat** [SciML/NeuralPDE.jl#706]
I've noticed that this package is sucking up a lot of CI time.  I will never argue for running fewer tests as I love good test coverage, and I understand that numerical projects such as these just can't use toy problems that are quick to solve to give good test coverage.

Examining [an exemplary test run](https://buildkite.com/julialang/neuralpde-dot-jl/builds/1677), I see that this run took ~20hs of CI time, the majority of which is in `NeuralAdapter`.  Logging into the test machines, I noticed that all the Julia processes were pretty much single-threaded.  Is there a way to split the tests into separate pieces that can be run in parallel on a single machine?  If not, fine, we live with it.

**Comment by sathvikbhagavan** [comment]
Now, we have all the test suites to run under one hour. @ChrisRackauckas, can we close this?
