### ISSUE TITLE
NeuralPDE v.5.9 stops QuasiMonteCarlo from updating

### ISSUE THREAD

**Issue by arthur-bizzi** [SciML/NeuralPDE.jl#748]
Hey.
I'm having trouble updating `QuasiMonteCarlo` through the REPL. When asked, `pkg` tells me it's  `NeuralPDE`'s fault:
```
(@v1.9) pkg> status --outdated  QuasiMonteCarlo
Status `C:\Users\55619\.julia\environments\v1.9\Project.toml`
⌅ [8a4e6c94] QuasiMonteCarlo v0.2.19 (<v0.3.2): NeuralPDE

(@v1.9) pkg> status NeuralPDE
Status `C:\Users\55619\.julia\environments\v1.9\Project.toml`
  [315f7962] NeuralPDE v5.9.0
```

QMC version 0.2.19 is almost one year old by now. Is this easy to solve or does NeuralPDE use old QMC code internally?

**Comment by xtalax** [comment]
I'm looking at this now

**Comment by AstitvaAggarwal** [comment]
is this solved now?

**Comment by ChrisRackauckas** [comment]
I don't think so. QMC still needs updating here and Surrogates.jl I think, Surrogates.jl being the bigger and harder one.

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas can this and https://github.com/SciML/NeuralPDE.jl/pull/749 be closed as QMC is updated now.
