### ISSUE TITLE
DGM Tutorial fails

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#827]
The DGM tutorial fails as:

{
	"name": "LoadError",
	"message": "UndefVarError: `DeepGalerkin` not defined",
	"stack": "UndefVarError: `DeepGalerkin` not defined

Stacktrace:
 [1] top-level scope
   @ In[2]:34"
}
NeuralPDE v5.12.0

**Comment by ChrisRackauckas** [comment]
It just hasn't been released yet, it's on dev.

**Comment by finmod** [comment]
👍 Now tgrid and xgrid are missing in the graph
