### ISSUE TITLE
Tutorial: imposing constraint on PINN solution of Fokker Planck fails

### ISSUE THREAD

**Issue by finmod** [SciML/NeuralPDE.jl#854]
This example from the cited paper should be run for three values of alpha as an example of nonadaptive loss with equal weights on each loss. Two runs out of three fail as shown in the following graphs.

![FPEX0 3](https://github.com/SciML/NeuralPDE.jl/assets/12710434/dc4ce354-0858-4aa6-b4b1-aa93a51deeaf)
![FPEX0 5](https://github.com/SciML/NeuralPDE.jl/assets/12710434/b2459d2c-4075-4329-8581-72051546ba67)
![FPEX0 7](https://github.com/SciML/NeuralPDE.jl/assets/12710434/93104e25-7baa-4326-98cc-03eea1d6628d)
to be compared with Figure 2 in the referenced paper.

The plot of the "alpha = 3" run appears to be spot on but does not always give "success".  

I have tried all the available strategies and adaptive losses to no avail. Is it an optimization problem? 

This tutorial on the FP equation is important and should be reliable not only on this example but also on the other examples mentioned in the reference. Otherwise, NeuralPDE is simply not robust enough for any experiment.

**Comment by AstitvaAggarwal** [comment]
Hi, the scaling factor C affects the actual predicted and analytical fits. for the case of alpha=0.7 let C=37. you would get something like this 
![image](https://github.com/SciML/NeuralPDE.jl/assets/84859349/e5047da3-af3f-4175-b124-23dcc0e51021)

**Comment by AstitvaAggarwal** [comment]
refer to : https://arxiv.org/abs/2309.16725 regarding the Relation between the Normalization constant C and alpha, beta etc. It ensures that the integration of the probability density function P(x) across entire domain of x integrates to 1.

**Comment by AstitvaAggarwal** [comment]
Now this becomes an optimization issue, so run the solver for 2000-3000 iterations and the inner norm integration solve call for 20 iterations. ( The original paper has used many more iterations than 600). I get your point regarding the tutorial, I'll extend it to the other cases as well.

**Comment by finmod** [comment]
@AstitvaAggarwal Extend the FP tutorial to scored-based PINNs for HimDim FPEs  https://arxiv.org/abs/2402.07465. NeuralPDEs possess all the elementary ingredients.
